### ISSUE TITLE
Weirdness with day and time in Otherside world

### ISSUE THREAD

**Issue by Gyztor** [elBukkit/MagicPlugin#1052]
i'm honestly not sure what exactly to say other than when i  try to set the time to midnight (wether using cmi, minecraft's default or anything similar) it attempt to resist my changing the time, this behaviour has only ever been seen with the otherside world. on top of that it's even resistant to the magic that makes it night time here is a video i recorded of it happening
[https://www.youtube.com/watch?v=inunafrb-Tw](url)

EDIT: there is also no error logs about it anywhere

**Comment by NathanWolf** [comment]
The otherside time is locked to be the opposite time of the main world.

If you'd like to turn this off you can turn this off with `/mconfig world otherside_blocks synchronize_time false`

That said, I *think* it's supposed to handle this by changing the time in the main world if you chain time in the otherside world, so I will leave this open until i decide if that's true. I may have changed my mind on that since it might be surprising and annoying.

**Comment by Gyztor** [comment]
thank you so much i have been looking for a fix for this XD
