### ISSUE TITLE
Action hot bar issue for 1.19 viaversion

### ISSUE THREAD

**Issue by 0MrCrazy0** [elBukkit/MagicPlugin#1064]
hello installed viaversion to allow 1.19 players to join my 1.18.2 server. the wand hotbar has a small issue u can see the white boxes. all good for 1.18.2 players.
![2022-06-10_11 17 22](https://user-images.githubusercontent.com/102135865/172971008-0faebaeb-483d-46c2-b9b4-c2740525641b.png)

**Comment by 0MrCrazy0** [comment]
Hi, :) I will remove via version once paper 1.19 is out & when most of my plugin have 1.19 support. I am using forcepack plugin to force RP on players when they join. & use https://mc-packs.net/ to host my RP. I can update it anytime. So I guess just what for updated Magic RP-HRes.

**Comment by NathanWolf** [comment]
This is not actually an RP problem (well, not exactly)

There is a space in the hotbar message that shouldn't really be there. MC 1.18 would render this as a space even if using a custom font that has no mapping for the space character- 1.19 does not.

This will be fixed in the next dev build, simply by removing the space from `wands.gui_actionbar.requirement_properties.properties.action_bar.message`

**Comment by 0MrCrazy0** [comment]
Hello again i have updated to full paper 1.19 & using magic dev build 10.8.  Now same issue with the small white box on the last slot & the hotbar also its blinking non stop when holding wand.

**Comment by 0MrCrazy0** [comment]
so i removed my gui.config in my wands folder its removed the cool hotbar but now it shows spell name when right clicking kinda like it.

**Comment by NathanWolf** [comment]
I think you can put the hotbar back now if you want, the issues should all be resolved.
