### ISSUE TITLE
[Request] Otherside doesnt replace blocks below Y = 0 yet.

### ISSUE THREAD

**Issue by Remodactyl** [elBukkit/MagicPlugin#1109]
Worlds have now been updated to have heights all the way down to -64, but the otherside doesn't seem to be configured to handle this yet. The otherside will still generate regular Deepslate caves and resources below this point that are not replaced by the block replacement configuration.

**Comment by NathanWolf** [comment]
I *think* all the code has been updated to look below y=0, however I never added replacement rules for any of the "deep" blocks. I'll try and take a look at this when I can.

**Comment by Remodactyl** [comment]
I made modifications to the materials customization for a custom otherside (including all the deep blocks), but blocks that are being replaced above ground such as lava, gravel etc are not being replaced below 0. It definitely still has something to do with the boundaries it looks for. :/

**Comment by NathanWolf** [comment]
This will be fixed in the next dev build and release 10.8.4
There was in fact a default of 0 - 255, which I have removed.

I also added replacement for deepslate and tuff ... it'd be fun to do ancient cities but I didn't have the energy for that XD

If you happen to make rules for that yourself and want to share, it'd definitely be appreciated!

**Comment by Remodactyl** [comment]
I didn't even think about Ancient cities, good call!

**Comment by Remodactyl** [comment]
Verified that this is working now so closing issue
