### ISSUE TITLE
Recall Spell

### ISSUE THREAD

**Issue by iKezzaUK** [elBukkit/MagicPlugin#118]
Hi, I recently installed your plugin onto my server, and realised that the recall spell doesnt work, there is no list of places to go. How would i add places to that list?

**Comment by NathanWolf** [comment]
You have to customize the spell, how would it know where you want it to go otherwise?

It can work with warps from Essentials or CommandBook.  See here for an example of how to customize it:

https://github.com/elBukkit/MagicPlugin/blob/master/src/examples/elpotter/spells.yml#L10

The "warps" block specifies warps, the "commands" block specifies commands to be run.
