### ISSUE TITLE
Effect on teleport

### ISSUE THREAD

**Issue by Blamo27** [elBukkit/MagicPlugin#127]
The player still have effect when he's teleporting in another location (MobArena).
Can you add an option in the config to fix this ?

**Comment by Blamo27** [comment]
@NathanWolf ?

**Comment by NathanWolf** [comment]
Sorry, I must've missed these original emails 

Um, so you would like an option to clear all potion effects on teleport? I have to imagine there's a stand-alone plugin out there that does that .. I'd also be really surprised if it's not a MobArena feature! If not, it would be easy enough to add to Magic, just feels like a bit specific, maybe.

Potion effects added by spells aren't really tracked like that, so it wouldn't be possible (or at least not easy) to just cancel effects caused by spells.

**Comment by Blamo27** [comment]
An option to clear all potion effects on teleport or check if player is still equiping the Magic armor.

And MobArena is really bugged, there are a lot of bugs.

**Comment by Blamo27** [comment]
And I have another issue too, is there a possibility to cancel the track spell for the vanished player
(/vanish of essentials).

Thanks.

**Comment by NathanWolf** [comment]
Magic armor (or wands with potion effects) will instantly re-apply those potion effects on TP. So that may be an issue for you, and not easy to fix without some deep MobArena integration (not likely anytime soon, honestly).

Disallowing targeting of vanished players sounds like a good idea, though. I'll open a separate issue for that.

**Comment by Blamo27** [comment]
You can't use the teleport event to re-apply the potion effects ?

**Comment by NathanWolf** [comment]
Re-apply? I thought you wanted them cancelled?

**Comment by Blamo27** [comment]
Oh, I didn't think your plugin worked that way. I thought that your plugin checked if the player was wearing an armor, in order to apply or not the effects to a player whenever an event occurs.

**Comment by NathanWolf** [comment]
I think that is more or less true, but "event" in this case can be anything- like changing equipped items. You'd really need something to prevent the effects being added, unless (I suppose) their armor and wands are stripped away when entering an arena.
