### ISSUE TITLE
Magic Mobs with "Protection" cause brief server lag.

### ISSUE THREAD

**Issue by LowFiPies** [elBukkit/MagicPlugin#1298]
Hello,

I noticed that Magic Mobs with "Protection" tags such as Fall, Burn, Magic, Projectile... cause brief server DPS drop upon spawning them.

https://github.com/elBukkit/MagicPlugin/assets/14805141/f672ac4a-f792-4280-b5fc-66aa8e41462d

I provided a video showing the bug.
**The command block is simply spamming placing a block, and when it stutters, it means the server lagged.** Everything in the server freezes when they spawn.

As you can see from the video, spawning normal mobs without "Protection" causes no issues. On the other hand, if that same mob with "Protection" is spawned, it freezes.

I am using the latest Magic Dev build (Magic-10.8.13-SNAPSHOT) on latest Paper 1.20.4.
This bug also happens on the latest Magic version on spigot (10.8.12).

**Comment by NathanWolf** [comment]
Can you share your mob config for both cases?

How are you spawning the mobs? If it's with a command can you share that too?

**Comment by LowFiPies** [comment]
Everything you asked for should be in the video. Are you able to see it?
I'll share them just in case:

(Normal mob that causes no lag)
```
testnormal:
  type: zombie


```

(Mob that lags upon spawning)
```
testprotection:
  type: zombie
  protection:
    fall: 99
```

I am spawning them with the command "/mmob spawn xyz"

**Comment by NathanWolf** [comment]
Do you have any other way to check server TPS or lag?
Do other players that are nowhere near this also experience the lag?

Are you able to install the spark plugin or otherwise generate some timings?

I could not reproduce anything like this myself. I spawned 100 protected zombies in a go with no TPS drop and nothing showing up in Spark.

My initial reaction was that this is *somewhat* hard to believe and there has to be something else going on here. The only thing I can think of is if you have mobs trying to load mage data, but that is off by default. Have you set `save_non_player_mages: true` in configs?

Even that is kind of a stretch since player/mage data is loaded asynchronously.

Otherwise these protection blocks are just setting some properties on the mob that won't really do anything until they take fall damage. The initial construction of their mage objects shouldn't have a performance impact, but that's the only thing extra that's really going on when you have a "protection" tag on the mobs.

**Comment by LowFiPies** [comment]
I should've mentioned, I was basically running "/mmob spawn testprotection 50" then "/mmob clear all 100" over and over. Each time I waited for the server to respond again, which took around 3-4 seconds.

**Comment by NathanWolf** [comment]
The `save_non_player_mages` config would be in config.yml, you can check the file directly or use `/meditor config` to see your customizations.

Looking at the spark profile (very helpful, thank you!) it does kind of look like that's turned on- which would make these commands equivalent to 100 players logging in and out constantly.

I'm going to keep looking, there's probably some optimization that could be done to player data loading, but it's definitely not set up to handle that kind of login/logout volume.

**Comment by LowFiPies** [comment]
I'm looking through my config file, and I think it is set to false:
```
 Enable this to persists Mage data on mobs.
 This can generate quite a lot of save data if you have randomly spawning
 Mages, but it would also let you undo their spells after a restart.
save_non_player_mages: false
```

My config file has been there since 2020, could updates have corrupted something/prevented the new settings to load?

**Comment by NathanWolf** [comment]
Hm, probably not though generally your config shouldn't have the default values in it, probably not a big deal.

If you're able to test a dev build I'll have some optimizations ready soon, maybe it's not file related and I'm just not seeing the impact without it. I am testing on my laptop, if you're using a hosted VM or something it's possible the performance hit is worse for you?

**Comment by NathanWolf** [comment]
If you can, please try this dev build when it's done:

https://jenkins.elmakers.com/job/MagicPlugin/4264/

I was able to optimize loading quite a bit, though it's maybe still a little expensive if you're really planning on spawning 100's of these at a time.

**Comment by LowFiPies** [comment]
Yes, I'll be able to test any dev builds.
I'm testing it on my server which is hosted on a normal hosting website, I'm not hosting anything on my own.

Usually I'm not spawning that many of course, it was just to make it more clear that it is causing problems.

**Comment by LowFiPies** [comment]
Great news! Immediately 10x better. No stuttering now!
Thank you so much for your quick responses and patience!

**Comment by NathanWolf** [comment]
Well that's good news!

I'l like *90%* sure that was a safe optimization ... 😅
