### ISSUE TITLE
How do I disable spells.

### ISSUE THREAD

**Issue by Fancepants** [elBukkit/MagicPlugin#161]
I would like to disable some spells or make the cost something like 99999999999 so they can not buy it via a enchanting table. I tried to edit the spells.default.yml but this just reverts back. I couldn't find a guide that would assist. Can you Help?

**Comment by NathanWolf** [comment]
https://github.com/elBukkit/MagicPlugin/wiki/Customization#customizing-spells

The important thing is "never edit the defaults". They're not editable :)

To disable a spell, you put something like this in plugins/Magic/spells.yml : 

```
nuke:
  enabled : false
```

The defaults are there only for reference. In order to ease upgrading it's best to only put the modifications you want to make in your customized configs, these will override anything in the defaults.
