### ISSUE TITLE
Damaged item variants

### ISSUE THREAD

**Issue by meneertimmy** [elBukkit/MagicPlugin#166]
I believe that it was already possible to use damaged item variants as wands if you change the wooden hoe's in the resourcepacks but can I also use this as iron or diamond hoe's. If I try this I get only a purple block.

**Comment by NathanWolf** [comment]
That sounds like an issue with your resource pack. You can use whatever item variants you want, yes. 

You generally have to make the wand indestructible (otherwise it may change appearance if damaged, which could happen via vanilla behavior) but otherwise there's no special trick to it. 

Purple+black block means your RP is broken in some way, or you've put an invalid damage value on a tool.
