### ISSUE TITLE
QuestsWorld 2 plugin support.

### ISSUE THREAD

**Issue by Hatoskahun** [elBukkit/MagicPlugin#191]
Could you add Questsworld2 plugin support? (https://dev.bukkit.org/projects/quest-worldhttps://dev.bukkit.org/projects/quest-world)
I mean if someone kill a mob with magic the quest plugin doesn't count the mobs.

**Comment by NathanWolf** [comment]
I think you have two good options for that:

1. Ask the plugin dev of Questsworld2 to support thrown potions. If you get credit for killing a mob with a splash potion of harm, then spells should also work.

2. Change your Magic configs to use direct damage rather than magic damage. You can do this by adding the following to your spells.yml:

```
override:
  parameters:
      magic_damage: false
```

**Comment by Hatoskahun** [comment]
niceee thanks!
