### ISSUE TITLE
[1.9+ Duplication glitch]

### ISSUE THREAD

**Issue by Svennieboy777** [elBukkit/MagicPlugin#211]
Hello there,

One of my players have noticed a duplication glitch that starts when you have your wand in inventory mode. If you got a wand and you right-click it then it will open the inventory mode, if you click on (default) F to move the wand to your second hand while enabling the inventory mode, the wand will duplicate.

If you got any solutions to this, please let me know

Thank you for your help

**Comment by NathanWolf** [comment]
What version of Magic? I don't think it's done that in a very long time.

**Comment by NathanWolf** [comment]
After some experimenting I was able to get to this to happen, not always, but sometimes if I use the swap button while the wand is open.

I think it may be related to not having an action (like cycle hotbar) bound to swap.

I will keep on this and get it fixed!

**Comment by NathanWolf** [comment]
If the specific issue had to do with wands that don't have a "swap" action then this should be fixed in the current dev build.

All wands in the default configs have a swap action (set to toggle hotbar) so you would have to have some completely custom wand configs that don't use the swap action.

If that doesn't sound like your issue, or if you still see the problem in current dev build (will be released as 6.8) please let me know.
