### ISSUE TITLE
[Wand chest bug]

### ISSUE THREAD

**Issue by Svennieboy777** [elBukkit/MagicPlugin#231]
Hello,

A player of us found a bug, which can transport your wand into anything that you can place it into, such as a furnace, chest, and others. To do this you must first enter the chest, place an item in the chest, hold the mouse over the item you put in, and then press the number of your hotbar that has your wand in it. Basically, you can transport your wand in by switching the two items places.

I hope you can fix this bug,

Thank you,
Svennieboy777

**Comment by NathanWolf** [comment]
I'll see what I can do there- think it's a bit tricky since I can't just look at the item being "clicked" on (in this case having a number key pressed on it), I need to figure out via the key that was pressed the item in the destination slot, then check that one. Probably doable though.

You should also be aware that I have turned all of this off by default in recent builds. As I move to 7.0 I am aiming to make wand items less "special" and in general would like players to be able to drop them and definitely put them in chests, if they want to. So when you get a chance, you should put this in your plugins/Magic/config.yml:

`wand_undroppable: true`

If you want to keep the current functionality to prevent putting wands in chests or dragging them out of your inventory.

**Comment by NathanWolf** [comment]
Fixed in latest dev build, slated for 6.9.9

Make sure to add "wand_undroppable: true" to your config.yml when you update.
