### ISSUE TITLE
Option to disable all magic block damage globally?

### ISSUE THREAD

**Issue by mibby** [elBukkit/MagicPlugin#233]
Is it possible to disable all magic block damage globally? As I noticed using the default magic missile spell with a new wand, I am able to break blocks. I'd like to cancel all block damage outright, not have blocks break and reappear after a short period of time.

**Comment by NathanWolf** [comment]
This may work in spells.yml:

```
overrides:
   parameters:
       destructible: air
```

But might mess with some spells.

The short answer is no, there is no easy way. All of the spells I make take advantage of block effects because otherwise they'd all just be projectiles that basically look the same. 

You'll have to make your own completely custom configs to really accomplish this.
