### ISSUE TITLE
About Resources Security Problem.. 

### ISSUE THREAD

**Issue by Kuroyabumozu** [elBukkit/MagicPlugin#244]
When wands destroy chest by any spells , the items will spout out on the ground from destroyed chest, and after few seconds the chest will be recovery as original looks, right ! , and the same items will be recovery too, and this problem will be make items going to duplicate, I mean the chest is destroyed the items will be duplicate/copy, and whenever you do this the items will be duplicate/copy over and over again!

does someone know how to solve this problem?

**Comment by NathanWolf** [comment]
What version of Magic are you on?

I assume this is more limited, Blast for instance doesn't do it- but Fireball and Boom do?

This bug was fixed a long time ago. I'll check for regression, but we may have to look at other plugins you have.

**Comment by NathanWolf** [comment]
I tested this with Fireball, Boom and Blast- none dropped items. Chest items are cleared whenever Magic removes a chest, which is how it is supposed to prevent this issue.

If you are not on an old version of Magic where this bug was still present (it'd have to be pretty old, I think, unless I missed a regression that was later fixed) then it may be some other plugin (like a protection plugin) getting in the way.

Please let me know any more details (magic version, protection plugins, etc) and I'll see what I can do.

**Comment by Kuroyabumozu** [comment]
My server using Spigot 1.11.2, and plugins are using what I downloaded latest dev_build version of Magic and MagicWorlds.
which is download from here http://jenkins.elmakers.com/ from Jun 7, 2017.
and the version is "Magic-7.0-SNAPSHOT" & "MagicWorlds-1.4-SNAPSHOT".

I was using the spells Magic Missile and Laser to test those bug above, maybe only this two? 
or other destroy spell could be too?

**Comment by NathanWolf** [comment]
Oooooooh - hm lemme check those two!

**Comment by NathanWolf** [comment]
Ok, thank you for the clarification and my apologies! The BreakBlock action (used only by Magic Missile, Laser and the war configs) was not clearing chest items.

This is fixed in dev build 2163: http://jenkins.elmakers.com/job/MagicPlugin/2163/com.elmakers.mine.bukkit.plugins$Magic/

And I will probably release this as 6.9.9 soon since this is a pretty bad exploit.

Thanks again!
