### ISSUE TITLE
Changeable lore

### ISSUE THREAD

**Issue by Worlfy** [elBukkit/MagicPlugin#286]
I'd like to be able to change this

![image](https://user-images.githubusercontent.com/8803519/34269608-5469bd84-e685-11e7-9b1a-882d56302b5b.png)

Into something like this

![image](https://user-images.githubusercontent.com/8803519/34269641-7aa5bea8-e685-11e7-9749-94eb9dbc4456.png)

Without breaking the wand / plugin

**Comment by NathanWolf** [comment]
Not currently possible, I’ll leave this open until custom lore support is implemented.

**Comment by NathanWolf** [comment]
Custom lore support is implemented, though you can't have it auto-generate a list of spells like that. You'd have to put the spells in lore yourself.

I just noticed you'd also like the spell to not show up in the item name - it actually should not if there is only one spell on the wand. 

Now you mention it though, it would be nice to have the option of not having the spell on the wand name, I can probably just use the action bar to show spell cycling.

**Comment by NathanWolf** [comment]
Oops, I forgot that the spell name is in the wand name because otherwise the hotbar mechanism doesn't work well, it'd flash spell names as you switch in a very ugly way.

So probably what's there now in terms of custom lore is as good as it's going to get, if you make a wand with a single spell the spell doesn't show up in the name and that's probably the best I can do.
