### ISSUE TITLE
The Path Block and Udoing

### ISSUE THREAD

**Issue by martdamp** [elBukkit/MagicPlugin#289]
Hey Nathan,

I'm back to report another bug.
When you cast a move that creates blocks on path blocks the path blocks will turn to dirt.
When the blocks from the move disappear the path blocks stay dirt.

martdamp
[A list of pictures showing what happens.](https://imgur.com/a/BbcJa)

**Comment by NathanWolf** [comment]
I did some testing on this, I think the main problem is there is no good event for grass paths fading to dirt.

I opened a ticket with Spigot that would let me fix this:

https://hub.spigotmc.org/jira/browse/SPIGOT-3735

Otherwise the only event that seems to work is BlockPhysics, and that is not one that Magic uses constantly since it fires extremely frequently in some case (falling water, lots of trees) and can cause lag.

Unfortunately this means in the meantime I can't see how to fix this.

**Comment by NathanWolf** [comment]
Well I got a super speedy response from Spigot! You'll need bleeding edge, specifically this commit:

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/dc7d31b00d121c486660fafc9d6b4eb38e9db76d

And the latest version of Magic, and this bug should be fixed.

**Comment by martdamp** [comment]
Thanks for the fixes
