### ISSUE TITLE
Possible to change mouse click settings?

### ISSUE THREAD

**Issue by xeniox** [elBukkit/MagicPlugin#297]
The only thing stopping this from working with McMMO as far as I can tell is that right-clicking runs on hoes already. Any chance there's a way I could set interaction with the wand to middle mouse button in order to open wand inventory?

**Comment by NathanWolf** [comment]
You can disable that feature of McMMO, I believe. Lots of servers have used Magic and McMMO together.

Otherwise, you can change wand interaction to the drop key, or the swap key- this upgrade item does exactly that, or you can change your wand configs accordingly:

https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/main/resources/defaults/wands/tweaks.yml#L21

put in you plugins/Magic/wands.yml :
```
base_wand:
    drop: toggle
    right_click: none
```

You can't use the middle mouse button, unfortunately, as the creative mode "pick block" functionality is entirely client-side.
