### ISSUE TITLE
HP Brooms

### ISSUE THREAD

**Issue by Curtis73** [elBukkit/MagicPlugin#3]
Hi, I have the Harry Potter configs for your magic plugin, and I think I have found an issue with the brooms. whenever I try to fly, in creative or survival, the broom flies out of my hand, comes back down again and says:your broom quiets down.

**Comment by NathanWolf** [comment]
Thanks for the report! That's odd, maybe the HP broom configs need updating, I'll take a look when I can.

**Comment by Curtis73** [comment]
ok.

**Comment by NathanWolf** [comment]
I just tried this out, and it seems to be working- you can see it on hp.elmakers.com (I stashed a chest of brooms behind Ollivander)

A lot of times this can be caused by WorldGuard - are you using WG regions with mob-spawning deny?

If so, you need to enable "plugin spawning" in the WG configs. Otherwise WorldGuard blocks Magic trying to spawn a horse (which powers the broom), and what you describe happens.

Please let me know if that helps!

**Comment by Curtis73** [comment]
Thanks so much!!!! - It worked!! now, my only question is how to put them into the broom vendor. I tried an npc with broom shop, but it didn't work.

**Comment by NathanWolf** [comment]
I don't have a broom shop in the potter configs. It'd be easy enough to make one, though.

You could also use Shopkeepers or some other shop plugin to sell them.
