### ISSUE TITLE
Wands do not get tagged as bound to a player until they hold it, and items detected wand_undroppable/wand_unstashable rely on that tag

### ISSUE THREAD

**Issue by malonnnn** [elBukkit/MagicPlugin#353]
Hopefully the title is descriptive enough, otherwise I'm happy to elaborate

**Comment by NathanWolf** [comment]
It is, but I think I would only like to fix part of this....

Wands not binding until held is intentional, to allow mods or other players to give someone a bound wand.

However, them being droppable or stashable is (I think) a recent bug, I will look into that part.

Please let me know if the auto-binding part is important to you, I could probably add a separate option, but it is something that can be a little frustrating when trying to give wands to players.

**Comment by NathanWolf** [comment]
It just occurred to me that there's a good work-around for this for now- try adding this to your config.yml:

```
# Commands like /mgive and /wand will bind wands to players
bind_on_give: true
```

**Comment by NathanWolf** [comment]
This should be fixed in latest release- wands will be unstashable immediately, though they still don't bind until held, unless you set the above config option (this is intentional)
