### ISSUE TITLE
Cost lore new line

### ISSUE THREAD

**Issue by Blamo27** [elBukkit/MagicPlugin#356]
Hello,

I would like to set two lines of text in "cost_lore" on items sold in magic shops. Something like : 
&5&oLeft click to buy 1 unit
&f&lCost : 1000$

So I tried : cost_lore: "&5&oLeft click to buy 1 unit\n&f&lCost : 1000$" but \n doesn't work. How can I do that ?

**Comment by NathanWolf** [comment]
Well one option is I change cost lore to support newlines, but I think a better approach would be to add a secondary message that would go in front of costs, where you would put just "&5&oLeft click to buy 1 unit".

Otherwise items that have multiple different costs (possible in the Selector at least, not actually sure bout ItemShop though) would look weird.

Would that work for you?

**Comment by Blamo27** [comment]
Yes, you can add an option to do that, it's better.
Thanks !

**Comment by NathanWolf** [comment]
Added to latest dev build as` shops.cost_heading`in messsages.yml

Can also be customized per-shop.

**Comment by NathanWolf** [comment]
Added in latest release!
