### ISSUE TITLE
Magic Item Shop issue

### ISSUE THREAD

**Issue by Elsopeen** [elBukkit/MagicPlugin#36]
Hello,
I found a bug with the Magic Item Shop spell when some of my players tried to buy something. I bound a NPC to the spell with the Magic integration of NPC plugin. When someone open the shop, the number of emerald in the inventory is marked as 0, while we have some. Unfotunately, this bug doesn't generate an error log in the console. I casted the spell without the NPC and it doesn't found my emerald in my inventory. I check the config files (default and custom ones) to see if I already modified something with the money but I didn't.
So, could you help me with this problem please ?
Best regards,
Elsopeen

**Comment by NathanWolf** [comment]
Are you trying to use the spell shop? If so, that uses SP by default now, not emeralds. You can change that with "use_sp: false" and "use_items: true" in the spellshop config, but the default configs do not sell spells for money.

Is that possibly the issue here?

To test this theory, you can try "/cast spellshop use_sp false use_items true"

![Spell Shop fo Monay](http://i.imgur.com/bF8BL2X.png)

**Comment by Elsopeen** [comment]
I don't use the spell shop (it's bound to another NPC, the professor, to make more role play), but the spell "magicitemshop" with which we can buy robes or a wolf house, but in the name of the kind of chest that is used, it's marked "Magic Item Shop (E0)" even if we have many emeralds in the inventory.

**Comment by NathanWolf** [comment]
Do you have Vault installed? You may need to add use_items: true to the shop config if so, otherwise it's working with virtual currency:

**Comment by Elsopeen** [comment]
We have Vault, so I think I'll try your advice and if it doesn't work, I'll contact you again, thanks

**Comment by Elsopeen** [comment]
The shop now works great, thanks a lot, again ^^
