### ISSUE TITLE
"Spell cast failed for progressmenu"

### ISSUE THREAD

**Issue by FuzzySlug** [elBukkit/MagicPlugin#360]
Hi, I recently put the magic plugin on my bukkit server, but whenever a player tries to use the enchantment table by right clicking with their wand, in chat it says "Something went wrong!" in pink, and in console it gives a long error, but it starts with "WARN [Magic] Spell cast failed for progressmenu"

**Comment by NathanWolf** [comment]
Have you done any customizations?

Do wands work at all? Any other errors in the logs, like at startup when the plugin loads?

**Comment by NathanWolf** [comment]
Also server and plugin versions would be good to know.

**Comment by NathanWolf** [comment]
That's pretty weird. Can you tell me if anything shows up in your logs when you do `/cast progressmenu` when holding a wand?

**Comment by FuzzySlug** [comment]
this is what console looks like when I do that, [](https://i.imgur.com/IaF8fzw.png)

**Comment by FuzzySlug** [comment]
https://i.imgur.com/IaF8fzw.png

**Comment by NathanWolf** [comment]
Oh right whoops, that was a known bug I fixed right away.

Honestly dev.bukkit.org is not a great place to get builds anymore. I barely remember to update there, and only because people still go there... but like really that whole team said screw you to the entire community and bailed years ago, I'm not sure why people still go there.

Please update to the most build on Spigot.. I'll update DBO

https://www.spigotmc.org/resources/magic.1056/history

**Comment by NathanWolf** [comment]
Eh, sorry for that needless rant. Were you able to get a working version of the plugin?
