### ISSUE TITLE
Mauto fountain

### ISSUE THREAD

**Issue by TofPlays** [elBukkit/MagicPlugin#373]
Mauto fountain particles don't work after server restarts, I'm not sure if it was intended to do so or if its a glitch. The spawner is still there tho without the particles.

**Comment by NathanWolf** [comment]
So you can still see it in `/mauto list` but the fountain doesn't work?

Could you tell me what version of the plugin you have (`/magic` will output)?

There was a bug at one point where if you put them in spawn chunks they wouldn't start on reload (because the chunks are loaded before the plugin loads) but I thought I had fixed that. I have some fountains at my spawn that work.

**Comment by NathanWolf** [comment]
If it's only slightly off (as it looks?) I'm guessing that is because the location is saved on block coordinates... 

I'm not sure why I did it that way, though, so I will change it for next release.
