### ISSUE TITLE
Player mobs

### ISSUE THREAD

**Issue by GrammaticaDW** [elBukkit/MagicPlugin#392]
hey, I am making mobs with your plugin.
But I have a problem.

I need a player mob. but I would like me to be able to put a skin on the server and that the plugin uses this skin for the mob.

I've already tried it with the disguise function. But when I change the skin of my account, the skin of the mob changes too. And this is not the intention for my idea.

I hope you have a solution for this or that this function can be added as soon as possible.

**Comment by NathanWolf** [comment]
This is not currently possible and I don't expect it will be possible soon. Mobs are config-driven, it would be difficult to add a way to specify an entire game profile in a config.

I'll keep this open as something to look into, but I would not expect it to happen soon.

Offhand, I could see adding a command that lets you dump a player's profile to the console as a base64-encoded string, then you could paste that into the mob configs, then magic could decode it, build an actual game profile and hand it to LibsDisguises. Sounds super complicated though.

**Comment by GrammaticaDW** [comment]
Thats a good idea.

**Comment by NathanWolf** [comment]
As it turns out I have supported this for a while without knowing it! You can put a serialized game profile (such as LibsDisguise's commands would save) into the config of a mob disguise as "skin".

I have also added a new command "/mage skin" to dump a player's current skin to chat so you can copy+paste it into a config.

There is now a built-in "ironman" mob that uses a serialized skin.
