### ISSUE TITLE
Players are able to drop spells out of their wands

### ISSUE THREAD

**Issue by christophe6** [elBukkit/MagicPlugin#396]
We released yesterday and we found a huge issue that several people are able to drop their spells. We're using exploitpatcher to stop the item duplication issue. I hope this is not a problem?

Proof: https://gyazo.com/95482e5a7f2e25607c788a8620a3c088 

I hope you could help us!

**Comment by NathanWolf** [comment]
It looks like the player just grabbed the spell and dropped it as normal. Is there any more to the bug than that? 

Clearly that doesn't happen in testing or I would've noticed ... if it's a plugin incompatibility of some kind it may be difficult to track down. If there's some other trick to it that would allow me to reproduce the issue then it's probably something I can fix.

My guess is it's an incompatibility problem though since no one else has reported it, and it seems way too simple to reproduce from your screen capture.

**Comment by christophe6** [comment]
Hmm... It seems like we fixed it for new players. But how can I delete all wand data of a player?

**Comment by NathanWolf** [comment]
What did you change? There's not much stored on player data (or wand item data) that would really affect this one way or the other. If you want to clear a player's spells, mana and other progression info, use "/mage reset <player>", or delete the file with their UUID in plugins/Magic/data/players.

If you suspect the problem is with their wand item itself you'd have to clear their inventory or use invsee to take the item away.

If you need to globally reset ALL wands on the server you can do that with a config change, which will make all the wand items inert.

But none of that should really matter in terms of spells being droppable. I'd love to know what the cause is.

**Comment by GrammaticaDW** [comment]
what we also hear from players is that players can no longer switch to their own inventory. But other players can do this.

**Comment by GrammaticaDW** [comment]
the normal items are also removed from the players.

**Comment by GrammaticaDW** [comment]
Also, some players can not change from spell. Very weird that we have so many problems now. We never had this. I do not know if it can be our own plugin. But I have a feeling that it is magic. But I don't know what we did wrong.

**Comment by GrammaticaDW** [comment]
update: we now know that there is a plugin that works against magic.

**Comment by christophe6** [comment]
No :/. We figured out that inventories were stored in a world where no player ever came ald we switched that to the main world which seemed to fix the issue but it didn’t.

**Comment by NathanWolf** [comment]
Is it just that they can drop spells? Or are all those other weird things still happening? This seems pretty game-breaking :(

**Comment by christophe6** [comment]
All the other weird things are still happening :/. We’ve tried a lot but we can’t figure it out and we didn’t have this issue on the older version of the server so it’s probably something on our side.
