### ISSUE TITLE
HP spell vendor.

### ISSUE THREAD

**Issue by Curtis73** [elBukkit/MagicPlugin#4]
Hi, I would like to report an issue with the spell shop in HP configs. Whenever I get a wand with /wand, and go to the vendor and right click to buy year 1 spells, it lets me. then once I have all Y1 spells except alohomora, it says there are no more spells to learn here. when I go to enchant it it says I need alohomora to advance. once I am at year 2 I go through the same process. but other players on my server can only get year 1 spells then it says there are no more spells for you too buy here. whereas I can get spells up to graduates. do you know why this is?? Thanks.

**Comment by NathanWolf** [comment]
That is by design, if I'm understanding you properly. The way I chose to set up the HP configs is that each year has an "exam" spell that a student must learn to advance to the next year.

https://github.com/elBukkit/MagicPlugin/blob/master/src/main/resources/examples/potter/enchanting.yml#L78

The spell shop doesn't sell this spell, it's meant to be obtained elsewhere. On my example server (hp.elmakers.com) I've got teachers set up throughout the school that players must find to learn the exam spells. On a real server these might be spells a player needs to take an actual in-game test to acquire and graduate.

As always these are just examples/suggestions. If you want a spellshop that includes required spells, you can add the following to your spells.yml:

```
spellshop:
  parameters:
     show_required: true
```

Then players can just buy their way through the years.
