### ISSUE TITLE
Multiple stream casts bypassing undo

### ISSUE THREAD

**Issue by grisstyl** [elBukkit/MagicPlugin#400]
When spamming the stream spell and standing still some of the water will remain without being undone.

**To reproduce**

1. Obtain a wand with the Stream spell
2. This wand needs to have cooldown and cost reduction on it
3. Cast the Stream spell a bunch of times while standing still

[My reproduction](https://gfycat.com/OptimisticTornBlacklab)

**Comment by NathanWolf** [comment]
Thanks for this!

As it turns out, the root issue is that two casts of the same spell in the same tick would end up sharing an UndoList. This resulted in the last few changes of the second spell cast not getting undone because the UndoList had already expired.

This should be fixed in the lasted dev build, I'll leave this open until it makes it into a release. Please let me know if you see it again after updating!
