### ISSUE TITLE
No difference between levels of buff

### ISSUE THREAD

**Issue by Ferocimo** [elBukkit/MagicPlugin#473]
Hello,

The wand buffs, specifically the physical one and the overal one (these are the only ones I've tested to be honest), are not propperly working. There is a difference between no Protection and Protection I buff, but there is none betwheen a Protection I and Protection V buff. 

We're using default config on these.

Thank you for looking into this when you'll have some time to spare.

**Comment by NathanWolf** [comment]
Have you made any changes to any of the damage_types config options?

https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/main/resources/defaults/config/damage_types.yml

I'll test it out when I can, it's been a while since I really paid much attention to it, but I'm not sure how it could've gotten broken in such a weirdly specific way.

**Comment by Ferocimo** [comment]
A little bit, but not in a way that should impact this I believe : 

> damage_types:
>   overall:
>     max_reduction: 0.2
>     max_strength: 5
>     max_weakness: 10
>   explosion:
>     max_reduction: 0.3
>     max_strength: 5
>     max_weakness: 10
>   fall:
>     max_reduction: 0.9
>     max_strength: 5
>     max_weakness: 10
>   fire:
>     max_reduction: 0.5
>     max_strength: 5
>     max_weakness: 10
>   physical:
>     max_reduction: 0.2
>     max_strength: 5
>     max_weakness: 10
>   projectile:
>     max_reduction: 0.4
>     max_strength: 5
>     max_weakness: 10
>   magic:
>     max_reduction: 0.4
>     max_strength: 5
>     max_weakness: 10
