### ISSUE TITLE
Spells upgrade 

### ISSUE THREAD

**Issue by LowFiPies** [elBukkit/MagicPlugin#5]
In the config. there's an option that says "Enable automatic spell upgrades"
If I disable it, spells wont upgrade by using them. However, I cant now give them upgrades spells by command. So if that option is disabled, I'm stuck with level 1 for ALL the spells. I dont want to enable it because I have like classes and some are cheap with weak spells, others are expensive and have powerful spells (higher level)
Please fix

**Comment by NathanWolf** [comment]
You can give higher-level spells. They follow a naming format, so if you want to give "Blink Level 3" it's "/mgive blink|3"

That weird character is a bar, it's normally shift+backspace.

The spell upgrades are really just separate spells that are handled in a special way due to their names- there is always a "|" character followed by the spell level.

**Comment by LowFiPies** [comment]
Yeah I'm aware of that. However, if I disable auto upgrade in the config so that players wont have automatic upgrades on wand uses, the entire upgrade system fails. So when I do /wand add Blink|3, It just gives me blink level 1. When I enable automatic upgrade and do the same, it works fine and gives me blink level 3.

*I fixed that in a kind of a different way by editing the 'spells' config and changing the upgrade option to "-1" to it never upgrades automatically even if I have the auto upgrade on.

**Comment by NathanWolf** [comment]
Ah, I see- yes you're right, the "enable_spell_upgrades" option turns upgrades off entirely.

I could add a separate option for disabling auto upgrades if that'd help you out. Having to customize every spell to turn off upgrades will be a pain.

**Comment by NathanWolf** [comment]
"enable_automatic_spell_upgrades" option added in the newest release, options clarified in default config file:

```
# Enable spell upgrades. Turning this off will make all of the upgraded spells
# unobtainable.
enable_spell_upgrades: true

# Automatically level up spells based on cast count
enable_automatic_spell_upgrades: true
```

This will be in 5.2 when it is released. You can use the option now in the latest dev build, but there are a couple of experimental changes in there that might have bugs.

**Comment by LowFiPies** [comment]
Cool! just one more thing that I'm not sure if already exists or you should add it.
How can I edit the wands names layout and lore. Like -> "Magic Missile (Master Wand)" and in the lore -> "Cooldown: A moment; Knows 3 spells" etc...

**Comment by NathanWolf** [comment]
The layout is not really editable- you can change all the text that appears, but not really where it appears.

Most of that text is in the "wand" section of messages.yml:

https://github.com/elBukkit/MagicPlugin/blob/master/src/main/resources/defaults/messages.defaults.yml#L109

Some of the text (like "a moment") is in the cooldown section since it is used in a few places, not just wand lore:

https://github.com/elBukkit/MagicPlugin/blob/master/src/main/resources/defaults/messages.defaults.yml#L233

If you want to remove some of the text completely, you can blank it out in your messages.yml - like

```
wand:
  spell_count: ""
```

I think that should prevent it from adding that line, I try to avoid adding blank lines in the code (though I haven't tested this out for every piece of wand lore)

**Comment by LowFiPies** [comment]
Oh, That's still acceptable. Now I know I'm getting annoying but its just because I really like the plugin.
Can the wands name be edited (at least colors) so like: [BLUE] Magic Missile ([YELLOW] Master Wand)?
If yes, where is it? I can't find it

**Comment by NathanWolf** [comment]
Unfortunately most of the colors are hard-coded .. however you could override them in the wand and spell names themselves if you wanted. You'd have to do this for every spell/wand though. 

So for instance if you wanted the Master Wand to be yellow, you could put this in messages.yml:

```
wands:
   master:
     name: "&eMaster Wand"
```

I think that giving you control over how the wand text is formatted would be better, but looking through the code it's kind of non-trivial. It's got stuff like this:

```
if (brush != null && spell.usesBrush()) {
				name = ChatColor.GOLD + spell.getName() + " " + getBrushDisplayName(messages, brush) + ChatColor.WHITE;
			} else {
				name = ChatColor.GOLD + spell.getName() + ChatColor.WHITE;
			}
```

So it's like a complex series of rules that build the names of spells and wands with specific colors meaning specific things.

I think ideally I'd give you templates to use instead, but I'd have to go through and find all the different cases and make templates for them. It's a good idea, I'll add it to the TODO- but unfortunately not something I can do right away.
