### ISSUE TITLE
1.14.2 spell schematics

### ISSUE THREAD

**Issue by Yukyxy** [elBukkit/MagicPlugin#510]
Hello, the spells tent / cage / tag doesn't works .
The spell tent / cage all schematics spells no longer work.
the tag spell tells me impossible to put a sign.

**Comment by Elsopeen** [comment]
Hi ! I checked the logs from my game (same problem, but with every schematics spell), and the problem comes from the NMSUtils.getPosition() function in which the Double type cast is not allowed. A possible modification could be a cast into Integer, then in double as `Double(((Integer)[value]).doubleValue())` to solve it.
Due to a encoding error (I tried to fix it on Windows, but the code has been written on Linux or at least a unix base), I couldn't try if it works.
Here's a log where I tried to cast the Wolfhouse spell
[latest.log](https://github.com/elBukkit/MagicPlugin/files/3242574/latest.log)

**Comment by NathanWolf** [comment]
This should be fixed in the latest dev build- thanks!
