### ISSUE TITLE
impossible to pickup item on the ground

### ISSUE THREAD

**Issue by Yukyxy** [elBukkit/MagicPlugin#553]
Hi, (spigot 1.14.4) 
from time to time it is impossible to pickup the items on the ground, 
as long as the player has his wand in slot 1 or 2 or 3 or 4 or 5 or 6 or 7 or 8 or 9 
he will not be able to pickup any item from the ground.

If he moves his wand in his inventory he will pickup the items on the ground! 
Please could you fix this problem?

**Comment by NathanWolf** [comment]
If you have a full spell inventory you can't pick up items with it open. The wand attempts to avoid this by leaving some slots open, but it's possible to get full. You'd have to move some spells by hand to the 2nd page.

Otherwise, there's nothing special there when the spell inventory is open, it's just items in your inventory like normal. I'll do some testing when I can though.

**Comment by Yukyxy** [comment]
the players have this problem when they are not in magic mode precisely.

**Comment by NathanWolf** [comment]
Hm, I don't think this plugin does anything at all special with item pickups if the spell inventory is not open.

Does it happen even if they're not holding the wand? Just having it in a slot 1-9 is enough?

**Comment by Yukyxy** [comment]
If they don't hold the wand in the hand or in the slots 1 - 9 there is no problem they can pick up the items on the ground.
It happens from time to time not all the time.

**Comment by NathanWolf** [comment]
Are you still having this issue? I have not been able to reproduce it.
