### ISSUE TITLE
Feature Request: Per world spawn with wand config 

### ISSUE THREAD

**Issue by DevL0rd** [elBukkit/MagicPlugin#558]
I'd like to be able to define which world's you start with a wand in. And optionally permissions to define who gets what kind of wand on spawn.

**Comment by NathanWolf** [comment]
This will probably not happen, to be honest.

Have you tried looking for a per-world starter kit plugin or something like that?

**Comment by NathanWolf** [comment]
I still feel like this is something that'd be better done with a different plugin. Especially because I imagine you'd be using some per-world-inventory plugin and it'd be really hard to make them all get along together.

But that said, I will leave this open and keep the idea in mind if I implement #763 maybe I can make per-world starter kits.

**Comment by NathanWolf** [comment]
You can do this now with magic kits.
