### ISSUE TITLE
Texture Pack Overlap

### ISSUE THREAD

**Issue by Lothaedan** [elBukkit/MagicPlugin#593]
For my server, I use both plugins QualityArmor and Magic. Both have custom textures that require the diamond hoe texture to display the correct texture, meaning either one plugin works right or sometimes the other. If it is possible, am I able to replace the magic wand as another item instead of a diamond hoe?

**Comment by NathanWolf** [comment]
Yes, there are a few options. 

The easiest is to put `example: skulls` in config.yml

The diamond hoe is used for spell icons, switching to skull icons means the plugin won’t use the diamond hoe anymore.

Then it’s a matter of combining the two RPs, you’d want the wood hoe and sounds from Magic’s RP, or just take the full skulls RP that it’ll auto-download with that config.

2. Combine both RPs, moving Magic’s spell icons to a different item. You would have to edit spells.yml to change the icon of every spell you use, though.

3. I think I could make a config change that will make #2 a lot easier to do. I’ll probably do this since it seems like a nice convenience if you can wait a bit. Maybe do #1 for now.

**Comment by NathanWolf** [comment]
I've done the thing I said in 3. above. 

You can see instructions here:

https://github.com/elBukkit/MagicPlugin/wiki/ResourcePack#merging-with-other-resource-packs

This will require the latest dev build, here:

http://jenkins.elmakers.com/job/MagicPlugin/2904/

**Comment by Lothaedan** [comment]
Thank you so much this will help out my server alot.
