### ISSUE TITLE
Magic issue with kingdoms+ support

### ISSUE THREAD

**Issue by Svennieboy777** [elBukkit/MagicPlugin#596]
So, i used this option to let magic work with kingdoms:
generic_protection:
  - FabledKingdoms

When i have an explosive spells in my intentory (not even casting it) in claimed kingdom land, I keep getting spammed with the message from the kingdoms plugin: you cannot interact or break blocks in other land. Is there a way to fix this issue?

Been looking for a solution for a while, hope you can help me with it.

Thank you.

**Comment by NathanWolf** [comment]
Unless there is a way to turn off that message on the Kingdoms side, I don't think it will be fixable.

I have looked into adding direct integration with Kingdoms, but since it is does not have an API available via Maven it was problematic.

**Comment by NathanWolf** [comment]
This is still pretty problematic since Kingdoms is closed-source (as far as I can tell, they removed their GitLab repo) and premium.

I'm hoping you can just turn off those messages, or if not ask the dev to please add that as an option. You did pay them, after all, and it should be an easy option to add :)
