### ISSUE TITLE
Casting destructive spells sometimes destroys block data.

### ISSUE THREAD

**Issue by leveljaap** [elBukkit/MagicPlugin#609]
Hello. So uhh, spells like blast, nuke and collapse kinda mess with items in chests, rotation on stairs and such, doors, etc.

I tried collapse (level 2) on my stairs and it pretty much messed up every single stair it hit!
![2019-11-10 (1)](https://user-images.githubusercontent.com/19862248/68549095-ab5b1c80-03f4-11ea-9e1a-4dd09f17c0ea.png)

Is there a fix for this??

**Comment by NathanWolf** [comment]
Since I have not seen this myself nor seen anyone else report it, I worry it may be a conflict with some plugin you have. Do you have any odd protection plugins or anything like that?

Does the problem happen every time, or does it seem random?

If you can't narrow it down you may have to reconfigure the plugin to avoid the issue, or else disable it.

In the meantime you can put this in plugins/Magic/materials.yml:

```
indestructible:
- bedrock
- barrier
- ender_portal_frame
- pistons
- containers
- stairs
```

But I imagine that will just reduce the problem, if it's randomly not restoring block data you're going to have issues with tons of blocks.

To be clear, there is no "fix" for this unless we can find the problem. The plugin does save and restore full block data and tile entity data, and generally seems tow ork.

**Comment by NathanWolf** [comment]
I believe this should be fixed in newer versions of the plugin, full block data is saved for undo purposes now.
