### ISSUE TITLE
No damage

### ISSUE THREAD

**Issue by christophe6** [elBukkit/MagicPlugin#616]
Hi

We created a small pvp arena in our server but the spells do not cause any damage to the players. The PVP worldguard flag is set to true and I can’t think of something else getting in the way.. Do you have any idea what the problem might be?

Thanks in advance!

**Comment by NathanWolf** [comment]
By true you mean allow (or unset, since allowing pvp is the default)?

Magic also supports pvp checks from Multiverse, Factions, GriefPrevention, PreciousStones and Towny. Are you using any of those?

Failing all of that, if you have some plugin preventing thrown potion damage that may be an issue as well.

**Comment by NathanWolf** [comment]
Did you figure this out?

**Comment by christophe6** [comment]
Yes, thanks to you we enabled pvp in Multiverse.
