### ISSUE TITLE
1.9

### ISSUE THREAD

**Issue by HollishKid** [elBukkit/MagicPlugin#62]
Hello,

since updating to CB 1.9, and Magic accordingly, I get the following warn from console:

[Server thread/WARN]: [Magic] Unknown effect type explosion_huge

**Comment by NathanWolf** [comment]
That is odd, I haven't seen that- and the effect types didn't change, only sounds and biomes - explosion_huge should still be valid.

Do you know if this is coming from a particular spell?

**Comment by HollishKid** [comment]
I have no idea, no one is online, this is on startup ...

**Comment by HollishKid** [comment]
Moreover, when In Game, I get the follwing:

http://pastebin.com/r7yrLmMJ

**Comment by NathanWolf** [comment]
Something seems very broken there :(

Are there any other errors or warnings from Magic?

**Comment by HollishKid** [comment]
This is all console has given me so far ...

I did notice that my mana bar is not visible anymore though?

**Comment by NathanWolf** [comment]
Oh I just noticed craftbukkit.jar - I honestly have not tested for 1.9 CB compatibility at all, I guess I assume most people just use spigot.

I'll try this out when I can!

**Comment by NathanWolf** [comment]
Ok, I'm confused- where did this craftbukkit jar come from? When I use BuildTools I still get "v1_9_R0" but you've got "v1_9_R1" - is this a --dev build or .. something?

**Comment by HollishKid** [comment]
I got it here: https://getspigot.org/

Hope this is not ... illegal or something? :S

**Comment by NathanWolf** [comment]
Technically it may be illegal depending on your country of residence and enforceability of the DMCA by Wesley Wolfe, but I don't think anyone's coming to knock on your door anytime soon.

I'm just wondering where *they* got it, then. As far as I know Spigot 1.9.1 isn't released yet, MC 1.9.1 itself is only in snapshots. It sounds like I may have some updating to do when it comes out, or else getspigot's builds are just weird.

If you could, please try to get the current version of spigot from here: 

https://hub.spigotmc.org/jenkins/job/BuildTools/

Download BuildTools.jar, and run it from the command-line like this:

```
export MAVEN_OPTS="-Xmx2G"
java -Xmx2G -jar BuildTools.jar --rev 1.9
```

For more info: https://www.spigotmc.org/wiki/buildtools/

This is a bit more complex, but is the "proper" way to get Spigot/Craftbukkit and ensures you're not downloading something from anywhere shady. Once you get the hang of it, it's also really easy to stay up to date- you just run it again anytime you want.

Let me know if that helps, otherwise I might have to wait and see what 1.9.1 really looks like before I can fix any of these issues- sorry!

**Comment by HollishKid** [comment]
Thanks!
I followed your advice, I still get

[14:29:04] [Server thread/WARN]: [Magic] Unknown effect type explosion_huge

on startup.
No further errors so far.

**Comment by NathanWolf** [comment]
Well that's good to hear! I'm still trying to figure that one out, though. That message comes from trying to look up an "Effect" enum and not finding it- but that particular effect hasn't changed, so this is pretty weird:

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Effect.html#EXPLOSION_HUGE

I also don't see it in my own logs. Have you customized the Magic config at all? It shouldn't really matter either way, just looking for clues. Can you please let me know the output of "/version" from your server when you get a chance?

Thank you for your patience here!

**Comment by HollishKid** [comment]
[17:09:41] [Server thread/INFO]: This server is running CraftBukkit version git-Bukkit-e43b278 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)
[17:09:41] [Server thread/INFO]: You are running the latest version

And yes I have edited Magic a little, paying around with language and default template to fit into my french server ...

**Comment by NathanWolf** [comment]
Would you be willing to put your spells.yml on pastebin or in a gist so I could try it out? I think that's the only file I'd need. I'm a little stumped at how you could be getting that warning.

The warning itself should be benign, if everything seems to be working- but I'd still like to know what's causing it!

**Comment by HollishKid** [comment]
I changed only the language file:

**Comment by NathanWolf** [comment]
Ah, thank you! Ok, I see the problem now, this is fixed in the latest dev build.

I was using an Effect to play a specific particle, but that's only compatible with Spigot. Changed to play the particle directly along with an explosion sound, and I think it should be all good.

Thanks for your patience!
