### ISSUE TITLE
Crafting Permissions

### ISSUE THREAD

**Issue by mythguy1226** [elBukkit/MagicPlugin#620]
Hi, so I noticed that with custom crafting recipes I have access to use them but others on my server don't. I tried using perms given by the wiki but nothing is working. Is there a node I missed? or maybe something in my files for the recipes that should be changed?

**Comment by NathanWolf** [comment]
There are no permissions needed for crafting. The nodes are only there so you can negate them to *prevent* crafting.

Do you have any other plugins that may be managing crafting in some way?

**Comment by mythguy1226** [comment]
Well.. the default droup has -magic.* and then the sub groups for certain players will have access to certain things for magic, so I was wondering how I would give them back those perms to use crafting

**Comment by NathanWolf** [comment]
Why are you negating all permissions?

**Comment by mythguy1226** [comment]
Easier for me to control what players get back but I can just take that away and negate only perms that cause issues I guess

**Comment by NathanWolf** [comment]
If you want players to be able to craft, use wands and cast spells then default permissions should be OK.

Otherwise if you want to negate all that should be ok, maybe just give back magic.wand.craft and magic.wand.craft.*

How well negating and wildcards work also depends on your permissions manager, some don't really work at all with wildcards.

Here are all the permissions, but keep in mind none of the commands are available to players by default:

https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/main/resources/plugin.yml#L749

**Comment by mythguy1226** [comment]
Awesome thanks
