### ISSUE TITLE
Drop Key Casts Spells

### ISSUE THREAD

**Issue by mercurialmusic** [elBukkit/MagicPlugin#625]
Having a weird thing happen where hitting the drop key casts the active spell. Doesn't matter whether the wand inventory is open or closed, confirmed by several players with several keybinding setups including default and custom. No errors in console. Not a big deal -- just weird.

Using the Magic 7.8.1 release on CraftBukkit version git-Spigot-492a779-b98e2de (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

**Comment by NathanWolf** [comment]
This *may* be an obvious question, but have you customized the wand configs at all?

The drop key is set to cycle_hotbar by default, do you maybe have `drop: cast` in your wand configs?

**Comment by mercurialmusic** [comment]
I have some minor customization, but only added appearances. It's currently drop: cycle_hotbar. The weird thing is that it's doing both, which I should have mentioned, cycling the hotbar and casting at the same time.

**Comment by NathanWolf** [comment]
Hm that's really weird... I can't imagine why that would be, I don't even think some other plugin could do that.

As a test, would you mind showing me the output of `/wand describe` while holding a wand that's doing this?

If you want you can do `wandp <yourself> describe` from the server console so you can copy+paste instead of screenshotting.

**Comment by mercurialmusic** [comment]
Sorry this took a while. Output here: https://gist.github.com/mercurialmusic/69fbef029bcd5873bcbaac70eead3a12

I'll note it's doing it on all of the default wands. But, if it helps, I went back and tested a few older versions where I know it wasn't doing it before and it still did it, so it seems more likely that it's a thing with Minecraft/Spigot?

Is no one else having it happen? We didn't change anything between when it didn't happen and now, so it's a little baffling if it's just us.

**Comment by NathanWolf** [comment]
Hm- yeah weird! I have not had anyone else report it, and I it's not happening on my dev servers.

So maybe you're right if it's a MC/Spigot thing?

It's also *possible* that it's some other plugin ...

Does your arm swing when you use the drop key?  Spell casting is based on the arm swing animation, so if for some reason dropping items is swinging your arms that'd do it.

**Comment by Curtis73** [comment]
Just thought I'd add - I recently updated to 1.15.1 (Magic version 7.8.1), and I've got the same thing.

The arm does swing when the drop key's hit - you can see its behaviour here:
https://gyazo.com/0a5374a7e0470851f67c2e457118382f

**Comment by NathanWolf** [comment]
Thanks, Curtis- and yes I see it now. 

Hrm, that's unfortunate because that means it was a client change. Now that I look you can even see it just throwing down a vanilla item... I guess they wanted to make it more like you were throwing it rather than vomiting it out on the ground.

While I appreciate that, it's a bit of a pain for me! I'll see if I can figure something out, maybe I get the drop event before the animation and I can ignore it within some small time limit.

**Comment by NathanWolf** [comment]
The cooldown trick seems to have worked, this should be fixed int he latest dev build.
