### ISSUE TITLE
Mskills allowing spells to be used when path is changed

### ISSUE THREAD

**Issue by NeoFalcon1605** [elBukkit/MagicPlugin#626]
When a spell is taken from /mskills it can be used even if the player changes to a class/path that doesn't have the spell or that they haven't unlocked the spell for yet.

Using magic version 7.8 and mc version 1.14.4 (unsure what spigot version).

**Comment by NathanWolf** [comment]
Hm I think we had a feature for that- can you try adding `clean_on_lock: true` to your class definitions? I think that will take away their spells when switching classes.

If that doesn't work, let me know. I think it'd be a good idea to prevent it on cast as well, but you're right that I don't think it's set up that way currently.

**Comment by NathanWolf** [comment]
Example: https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/examples/elworld/classes.yml#L27

**Comment by NeoFalcon1605** [comment]
That didn't seem to work, it didn't take the spell from my inv and I could still cast it after changing class.

**Comment by NathanWolf** [comment]
So, turns out I did mean to prevent this but there was a logic bug where skill items wouldn't get their class assigned unless they were set to non-quick-cast.

This is fixed in the latest dev build (which I'm about to release as 7.8.2), please let me know if you still have issues!

One unfortunate caveat though, since this is a property of the item if players have skill items from before the fix they will still be able to use them.
