### ISSUE TITLE
Some spells destroy block without regenerate the block when I place a block in the target block

### ISSUE THREAD

**Issue by qsefthuopq** [elBukkit/MagicPlugin#629]
I sent a private message to you in Discord,please take a look.
Maybe it's hard to explain the bug for me,just look at the gif I uploaded in Discord:
https://media.discordapp.net/attachments/666882380191105045/669478990481719307/GIF.gif?width=500&height=298

**Comment by NathanWolf** [comment]
So if you place a block in the place of a block a spell destroys, it will not restore that block.

This is intentional... the plugin has a hard time knowing what to do in that case. Should it erase the block you just placed?

If this becomes an issue you can opt to make chests indestructible by adding it to the indestructible list in materials.yml, e.g.

```
indestructible:
- bedrock
- barrier
- ender_portal_frame
- pistons
- containers
```
