### ISSUE TITLE
deserialization issue on /magic reload

### ISSUE THREAD

**Issue by marvinej** [elBukkit/MagicPlugin#646]
[Tue, 18. Feb 2020 21:18:31 EST INFO] SirKratosAurion issued server command: /magic reload
[Tue, 18. Feb 2020 21:18:31 EST ERROR] Could not call method 'public static org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.deserialize(java.util.Map)' of class org.bukkit.inventory.ItemStack for deserialization
[Tue, 18. Feb 2020 21:18:31 EST ERROR] Could not call method 'public static org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.deserialize(java.util.Map)' of class org.bukkit.inventory.ItemStack for deserialization
[Tue, 18. Feb 2020 21:18:31 EST ERROR] Could not call method 'public static org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.deserialize(java.util.Map)' of class org.bukkit.inventory.ItemStack for deserialization
[Tue, 18. Feb 2020 21:18:31 EST ERROR] Could not call method 'public static org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.deserialize(java.util.Map)' of class org.bukkit.inventory.ItemStack for deserialization
[Tue, 18. Feb 2020 21:18:31 EST ERROR] Could not call method 'public static org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.deserialize(java.util.Map)' of class org.bukkit.inventory.ItemStack for deserialization
[Tue, 18. Feb 2020 21:18:31 EST ERROR] Could not call method 'public static org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.deserialize(java.util.Map)' of class org.bukkit.inventory.ItemStack for deserialization
[Tue, 18. Feb 2020 21:18:31 EST INFO] Wand crafting is enabled
[Tue, 18. Feb 2020 21:18:31 EST INFO] Skin-based spell icons disabled
[Tue, 18. Feb 2020 21:18:31 EST INFO] Loaded 0 attributes
[Tue, 18. Feb 2020 21:18:31 EST INFO] Registered attributes: [bowpull]
[Tue, 18. Feb 2020 21:18:31 EST INFO] Registered currencies: item,mana,xp,health,currency,sp,levels,hunger
[Tue, 18. Feb 2020 21:18:31 EST INFO] Loaded 6 effect lists
[Tue, 18. Feb 2020 21:18:31 EST INFO] Loaded 880 items
[Tue, 18. Feb 2020 21:18:32 EST INFO] Loaded 515 spells
[Tue, 18. Feb 2020 21:18:32 EST INFO] Loaded 6 classes
[Tue, 18. Feb 2020 21:18:32 EST INFO] Loaded 4 automata templates
[Tue, 18. Feb 2020 21:18:32 EST WARN] [33m Unknown or disabled spell prerequisite kill in path master, ignoring[0m
[Tue, 18. Feb 2020 21:18:32 EST WARN] [33m Unknown or disabled spell prerequisite kill in path knight, ignoring[0m
[Tue, 18. Feb 2020 21:18:32 EST INFO] Loaded 15 progression paths
[Tue, 18. Feb 2020 21:18:32 EST INFO] Loaded 143 wands
[Tue, 18. Feb 2020 21:18:32 EST INFO] Loaded 21 mob templates
[Tue, 18. Feb 2020 21:18:32 EST INFO] Loaded 20 crafting recipes

**Comment by NathanWolf** [comment]
Server/plugin version please?

**Comment by marvinej** [comment]
[Tue, 18. Feb 2020 21:27:47 EST INFO] This server is running Paper version git-Paper-105 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

Magic 7.8.2

**Comment by marvinej** [comment]
More Logs from this perhaps?
https://pastebin.com/QRHZKhwg

**Comment by NathanWolf** [comment]
Thanks, those logs are much more helpful.

Seems like maybe a bad material in configs- have you done any customizing?

**Comment by marvinej** [comment]
No i have not changed any of the default materials. I couldn't even find
where to do that.

**Comment by NathanWolf** [comment]
Strange, then. I'll update my test server in case something has changed, but I haven't seen this error. I don't ever test on Paper, but it'd be odd for that to make a difference here.

**Comment by NathanWolf** [comment]
Could you please try editing plugins/Magic/config.yml and add this line (on a new line at the bottom, no spaces or # in front)

`log_verbosity: 10`

Then start up the server and see what it says just before the error. There should be a message like "Loading XXXXX.yml" which will tell us the problem file.

Unfortunately the error itself is internal to Bukkit, it is trying to load an ItemStack from some config file and failing, so it's not something I can easily catch.

**Comment by marvinej** [comment]
https://pastebin.com/n36GrgMN

I don't see any sign of which plugin it may be.

**Comment by NathanWolf** [comment]
Hm is verbose logging turned on? I don’t see more log messages either.

If you have a way to zip up all your configs and link them here I could also try it out.

**Comment by marvinej** [comment]
https://drive.google.com/file/d/15nqA4XA3cbaBpuxVerReIvOJ4Dn0ibZU/view?usp=sharing

**Comment by marvinej** [comment]
ok i deleted all of the configs i didnt make any changes to. the only ones i changed were config.yml and spells.yml. And i restored all those other configs from the defaults folders. I'm not sure how or why any of the other configs got changed. It also sucks that there is no error catching that tells you exactly where the issue is in the configs. Recommend that feature.

**Comment by NathanWolf** [comment]
There should be, if you turn on verbose logging.

**Comment by NathanWolf** [comment]
(but I do agree with you, I'll see about putting the filename in when there's an error, even without verbose logging enabled)

Did you happen to keep a copy of the configs before you deleted them? I'd really like to know what was causing the error.

**Comment by marvinej** [comment]
but that didn't work as we both saw.


------
Respectfully,
Eli Marvin

**Comment by marvinej** [comment]
i sent a google drive link with a 7z of my whole magic folder before i
fixed it.


------
Respectfully,
Eli Marvin

**Comment by NathanWolf** [comment]
Oh thank you vey much, sorry I missed that.

**Comment by NathanWolf** [comment]
So log_verbosity was a chicken+egg problem... it's failing to load configs so it never gets to even read that. 

I've added a special error with the filename. Since Bukkit is responsible for parsing the files that'll be the best I can do, the error I get doesn't really tell me much more about what's actually wrong with the file.

For what it's worth, it is not ideal to copy all of the default configs like you've done here. It's not necessarily a problem, but it's also unnecessary and will make updates challenging.

**Comment by NathanWolf** [comment]
Ugh- so to make matters worse, Bukkit does not actually throw an error for this deserialization failure. All those log messages are coming from Bukkit itself, not from my plugin.

So I think I will print a warning when loading a file if Bukkit gives me back an empty Yaml, which I guess I will assume was due to some error. Kind of lame on their part.

The problem is somewhere in items.yml, it'd be one of those serialized ItemStacks but I can't tell which one.

**Comment by NathanWolf** [comment]
Documenting the full extent of this annoying problem, this is a soft-failure on Bukkit's side. So it is printing an error and skipping an item, but otherwise everything works.

This means I really have no way at all to tell that something went wrong.

I guess I could parse the file myself and figure out how many keys are supposed to be in it and compare with what Bukkit says, but jeez that's pretty hacky.

**Comment by NathanWolf** [comment]
For what it's worth, in the future I will tell people to track this down by using `/magic load` in-game. Since it will have parsed the config.yml already and turned on verbose logging that will at least let us know what file is causing the error logs.

Would be really nice if Bukkit was better about this, though. I suspect the problem is the "wood_hoe" items since that was changed to "wooden_hoe" but heck they should really log that.

**Comment by marvinej** [comment]
I'm honestly not surprised by any of this. My servers developer has to
write weird tricky nonsense around broken spigot/bukkit API all the time
and believe me i always hear about it.


------
Respectfully,
Eli Marvin
