### ISSUE TITLE
Bug since 1.13.X with Fences, Glass Panes and Iron Bars NOT connecting.

### ISSUE THREAD

**Issue by GrantisMantis** [elBukkit/MagicPlugin#652]
Check this clip here to see exactly what is meant: https://medal.tv/clips/20086268/d1337QpXUwi1

**Comment by XXY218** [comment]
This problem has been around for a long time, it would be great if it could be fixed :)

**Comment by NathanWolf** [comment]
Unfortunately it is unlikely that will be fixed. The problem has been around since block data was introduced, which is determined client-side when placing blocks.

So schematics will almost certainly never work. Placing blocks  programatically probably won't work either due to the complexity of computing the correct data given adjacent blocks.

Sorry.

**Comment by killme** [comment]
IIRC since 1.13, the implicit connectivity data was made explicit and moved to the server. So a proper schematic format should be able to store and place blocks that are connected *within* the schematic that is placed.

**Comment by NathanWolf** [comment]
Magic now supports Sponge schematics and the builtin schematics were all updated.

Spells like Place still won't properly connect blocks, I'm going to leave this open just in case there's some way to resolve that.

**Comment by NathanWolf** [comment]
Kind-of made Place work. Going to call it good enough unless I ever feel like spending more time on it.
