### ISSUE TITLE
Broomstick Config

### ISSUE THREAD

**Issue by kezzeur** [elBukkit/MagicPlugin#675]
Using the broomstick is a nightmare, it fails 99% of the time which just makes it very unreliable to use. Is there anyway to make it so it works everytime? Also how do I remove the global cooldowns?

**Comment by NathanWolf** [comment]
What version are you on? I thought the crashing on launch issue was fixed in 7.8.1, make sure you're up to date.

The cooldown can be changed like this in spells.yml
```
broom:
  parameters:
    cooldown: <milliseconds>
```

But note that it currently lowers with each broom level, so for completeness you should probably also override broom|2, broom|3, broom|4, broom|5. See broom.yml for details.

https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/main/resources/examples/survival/spells/broom.yml

**Comment by kezzeur** [comment]
yeah i figured it out you actually have to jump to use the broomstick, i felt pretty dumb but thx for the answer anyway

**Comment by NathanWolf** [comment]
Well you should not have to jump. There used to be an issue where it would hit the ground immediately, so you have to look upward or jump to get on it. But that should be fixed in recent versions.

**Comment by Zheka2025** [comment]
Hello, my broom is just hanging in the air and I'm sitting on it. She does not fly! what to do?

**Comment by NathanWolf** [comment]
Assuming you’re using Paper spigot, there’s some setting you need to turn off having to do with moveable armor stands @Zheka2025

**Comment by Zheka2025** [comment]
> Предполагая, что вы используете патрубок для бумаги, есть некоторые настройки, которые необходимо отключить, связанные с подвижными стойками для брони @ Zheka2025

**Tell me what you need to disable**
