### ISSUE TITLE
Magic Worlds

### ISSUE THREAD

**Issue by willy20041** [elBukkit/MagicPlugin#681]
Ok so could you explain how to make my world "other-worldly" im a noob with plugins and i just dont understand how to make my world look like that. i put all the scripts into my magicworlds folder and it seems like nothing has happened.

**Comment by NathanWolf** [comment]
So first you need to install the MagicWorlds plugin (copy MagicWorlds.jar to your plugins folder)

Then the config files from here: https://github.com/elBukkit/MagicWorlds/tree/master/src/main/resources/examples/otherside

should go in plugins/MagicWorlds/

These should get copied into plugins/Magic

https://github.com/elBukkit/MagicWorlds/tree/master/src/main/resources/examples/otherside/magic

Preserving folders (so the file in messages/ goes in plugins/Magic/messages)

If all that works you should be able to cast the Phase spell (/cast phase) to go to the otherside world.  Note that it needs to be a completely new world, otherwise you'll have to TP somewhere new to see the custom world gen take effect.
