### ISSUE TITLE
Error: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by apatuka** [elBukkit/MagicPlugin#698]
Hello i am using the version v7.9.5-d7da306 but it throws the following error
I'm running a fresh spigot install.

Here is the log:
https://pastebin.com/DM8Ww5UQ

I'm missing some dependency ? I downloaded this from Spigot

**Comment by NathanWolf** [comment]
That is a pretty strange error.

Given your previous question, did you perhaps build a custom plugin against an older version of MagicAPI, but package it into your plugin?

**Comment by apatuka** [comment]
Hello NathanWolf,

Fixed by adding depend: [Magic] instead of depend: [MagicAPI] at plugin.yml in one plugin i have the sourcecode.

Thanks

**Comment by NathanWolf** [comment]
Ok, but do be aware that's probably just a workaround, forcing Magic to load first so we get the currrent version of the API.

The real problem is that you're packaging the API in with your plugin, which you should not do. It might break other plugins that also try to work with the API. Make sure if you're using Maven that you have the API dependency set to "provided" just like you would with the Bukkit API.
