### ISSUE TITLE
Brooms not levelling

### ISSUE THREAD

**Issue by Curtis73** [elBukkit/MagicPlugin#700]
Hey,
I think I've found a bug relating to broom progression - I've tested this on a test server with the potter configs & the following versions of magic: 
7.9.3-SNAPSHOT-fc574d4  &  Magic 7.9.5-d7da306

On 7.9.3, the broom levelled up as expected, but on 7.9.5, each time I got off the broom after reaching the required_casts, the audio & visual effects of a level-up would play, but the spell itself wouldn't level up.
It might have something to do with classes, as I was able to get it to work after adding the wizard class to the broom.

**Comment by NathanWolf** [comment]
Thank you for the report!

Sorry about that- that definitely sounds like an edge case that got broken when I refactored all of the rankup / upgrade code to work without a wand.

There were always some special-cases in there for this one spell because when it gets upgraded you're not actually holding the wand. I thought this would work better with the new code, but apparently not- I will take a look as soon as I can.

**Comment by Curtis73** [comment]
No problem!
Got some bad news though - just tried running this on the latest dev build (7.9.6-6dd7924), and the issue persists. 
I have noticed that [this](https://pastebin.com/5g974gVB) error is thrown whenever it attempts to level up, so it's probably related.

**Comment by NathanWolf** [comment]
Ugh, sorry! I had not actually pushed the fixes :(

Please try again:
http://jenkins.elmakers.com/job/MagicPlugin/3062/

**Comment by Curtis73** [comment]
Ah - that did it!

Thanks again!
