### ISSUE TITLE
Magic Mobs not Spawning

### ISSUE THREAD

**Issue by mythguy1226** [elBukkit/MagicPlugin#738]
Hello, so recently I noticed that spawners for my Magic Mobs aren't working. Instead of spawning the mob I now get a warning in the console saying "Skipping Entity with id:<insert mob name>". Yes, the difficulty is set to normal, mob spawning is allowed on the server and within the regions I have spawners. Could this be a small error in one file that could be messing everything up?

**Comment by NathanWolf** [comment]
Sorry for the delay, I missed this report. I'll check the spawners myself, it's definitely possible they got broken somehow in recent versions of the plugin and/or server.

**Comment by NathanWolf** [comment]
Ok so I tested and they *do* seem to be working. You have to place them in creative mode (otherwise you get pigs) but they do seem to work.

Sorry about all the trouble. Another option is you can use the `/mauto` feature to set up spawners, this is a more flexible way to do it- but could be a lot of work if you have a ton of spawner blocks set up already. 

Let me know if I can help more!

**Comment by NathanWolf** [comment]
Are you still having issues with these spawner blocks?
