### ISSUE TITLE
Magic Skill Pack integration for Heroes with 1.16.1

### ISSUE THREAD

**Issue by angrykartoffel** [elBukkit/MagicPlugin#742]
Hi, Kainzo recommended I contacted you about any fixes to make the Magic Premium Skillpack work with the newest Heroes plugin.  I am currently running 1.16.1, with paper or spigot, and have tried to use your recommended configuration changes that you posted.  The skill pack still has not worked and am thinking they need to be recompiled from the information I gathered.  If there is a way to fix this already I would not mind learning this to detract from additional work.  Any help appreciated:  Here is the original message I sent to Kainzo:

I am having trouble finding any information on how to implement the skill packs properly for heroes, especially the ones that are added from the Magic pack.  I have downloaded the pack and placed the "skill.jar" files within the heroes skills folder as described in the directions.  When I enter the spell name for a heroes class, it does not recognize the ability.  I am currently running 1.16.1 with the newest Magic plugin and also your newest plugin for Heroes.  The default skills already included are working as intented.   The magic skills pack is the most recent also and has not worked for me.  For example, the heal ability is not recognized, but any default abilities that comes with Heroes Premium, like FullHeal, works fine.   Do I have to recompile the files? and if so, how does that work?

**Comment by NathanWolf** [comment]
I don't think the skill pack works with the newest version of Heroes. Heroes doesn't seem to update their Maven repo anymore so I'm not sure what I can really do about it.

**Comment by NathanWolf** [comment]
Sorry, I guess that's entirely fair. I guess what you could do if you have Heroes premium, is try to build against it.

The source for the skill pack is here: https://github.com/elBukkit/MagicHeroes

It should build like any other Maven project, so just `mvn package` after cloning it.

You can probably ignore all of the scripting stuff in there, the skill classes are all autogenerated from scripts but I'm hoping you wouldn't have to do that.

I guess all you'd need to do is reference the Heroes jar directly in the pom, and then see what's broken and hopefully fix it.

Alternately if the Herocraft team can update their Maven repo or point me to an update jar that'd work to. But I don't know if the free version is really compatible with premium anymore- I assumed that's why Maven stopped getting updated. But it also seems crazy if there isn't an easily-available current version to build against, if they still expect people to be making 3rd-party skills.

Anyway sorry for the terse response and bad news, but this has been broken for a while and I hit dead-ends pretty quickly in the past when I tried to update it. Let me know if you make any progress!

**Comment by angrykartoffel** [comment]
Thank you for all of your great information and will be trying this tomorrow.  I was able to contact Kainzo about this issue and he directed me to another user.  The basis of the information he did give me was about the repository you speak of.  Here is the info he was able to provide:

It would just be with this pack specifcally.  Our maven repo is up to date. (We use Nexus) 
Poke MysticMight about this please in Heroes Dev server.

Still waiting on a response from the user he provided.  It's been urking me also so I understand where you are coming from.  I think I have the puzzle pieces at least.  If I'm able to get more info I'll gladly post here.  Lots of dead ends and Google searches!

**Comment by NathanWolf** [comment]
Ok, please let me know what you find out!

Their Nexus is the one that I've been using is here:

http://nexus.hc.to/content/repositories/pub_releases/com/herocraftonline/heroes/Heroes/

I have been building against the 1.5.5 version, which is over 4 years old now. But it's still all I see in that repo.

Maybe they're thinking of the private version of the repo, and just haven't been publishing anything public anymore?

**Comment by angrykartoffel** [comment]
Entirely possible, I added an extra thought at the end of my last comment that may spark an idea.

**Comment by angrykartoffel** [comment]
Ok, so doing some review on anything I see within the source pack.  The source pack does show a repository with the link

http://nexus.hc.to/content/repositories/pub_releases

So what I did is travel back to the content folder and traveled to the last heroes folder that was last updated here:

http://nexus.hc.to/content/repositories/pub_releases/com/herocraftonline/heroes/Heroes-Parent/

Still looking into this but it is the first thing I found.  Will edit this comment for any findings I may find

**Comment by angrykartoffel** [comment]
![Capture](https://user-images.githubusercontent.com/47162907/92381916-a977ed80-f0d9-11ea-8a9e-39253b8bfe41.PNG)

**Comment by NathanWolf** [comment]
I don't think you can use the parent directly, and it's still a couple years old. Did that help you progress?

That eror you're getting looks like you're just missing Magic, you will need that in your plugins folder as well:

https://www.spigotmc.org/resources/magic.1056/

**Comment by angrykartoffel** [comment]
Hi Nathan, just another update here.  I didn't get much time to work on it today but I will be taking a step back to start over my project.  The individual that Kainzo recommended I talked to actually got back to me and said that he is currently working on it.  Not sure of the time frame but in the mean while I will continue to try and figure it out.  I'll have a new build tomorrow to test!

**Comment by angrykartoffel** [comment]
Hi Nathan, I was able to properly add the local jar to the project folder for Magic Heroes like we discussed previously so it reads from the latest version.  It made more sense what you said originally the more I read it.  Right now I'm actually stuck on the skill part.  I'm not sure If I'm supposed to somehow add the new repositories to the skill file or not.  This part is a little confusing to me.  At this point I may just wait it out and see if it works later, but I really like the spells you have.  Any more suggestions?

**Comment by NathanWolf** [comment]
Well- a not-so-humble suggestion, maybe. Do you already have a server set up using Heroes?

If not, what are you trying to get out of Heroes?

As for your experiments, did you try building the skills project after you've added the local jar? You'd need to update the version in pom.xml to match your new local version, but otherwise it should be as simple as `mvn package`

**Comment by angrykartoffel** [comment]
Well I think I'm mostly ambitious with just trying these skills because I liked watching them work as magic itself but I wanted them to get the skills based on levels like heroes does already.  Yes sir I do have a server set up that I test after any changes I make.  Basically I just wanted to use those skills and have it register as heroes spells from the class configs in heroes.  I currently use your suggested settings for Heroes integration.

**Comment by NathanWolf** [comment]
Ok - well I'm mainly asking because you might not really need Heroes.

I don't have "levelling" per se but there are a lot of flexible options for progression and D&D-style experience levels is also something I'm aiming to add for the built-in RPG configs, so it's something we could work together on if you'd be interested.

Mostly I'm wondering if you're doing all this work because you like Magic's spell system, maybe you are not aware that it also has a class system, attributes, skills, and just about everything else Heroes has got- maybe you can streamline your setup and side step this whole issue.

**Comment by angrykartoffel** [comment]
I would love to try and work on some leveling features I just don't have much experience with coding but I can do some testing.  I was just really used to the Heroes skills and I like the functionality of changing them within the class.yml file to my liking.  I just happened to come across Heroes and I like the integrations it offers, like the hotbar, cooldown timers.  I specifically not a fan of the wand mechanic and like the feel of shooting spells from hotbars.  I am more than willing to work on some different features that can work similarly, I just haven't done to much digging into the magic config until I had this issue which is why I am here now.  I wouldn't mind changing it to a class system rather than leveling for now, might even make it a little easier for me.  So I am more than willing to get a similar process working as of now as the server I am currently building is in dev stages.

**Comment by angrykartoffel** [comment]
I would be fine with closing this thread for now so you don't have an open ticket since there are already some people working on this issue.  If you use discord, my discord is Kartoffel#3891 .

**Comment by NathanWolf** [comment]
Great, if you’d like to join our Discord I’d love to continue this conversation!

https://discord.gg/Vk5nK5h

I’d suggest you try removing Heroes and see what Magic can do on its own. The easiest way to get started with the built in survival config is to grab a wand (`/mgive wand`) but that’s really just to get a class assigned to you. You could also do `/mage add mage` to add yourself to the mage class.

You can then use the `/mskills` menu and it works just like it does with Heroes. You can also try out the spellbook, `/mgive spellbook`, as an item replacement for the skills menu.

This plugin is *very much* opposed to players typing commands. The fact that Heroes has you typing `/skill Fireball` every time you want to use a skill is super awkward IMO. But the `/mskills` command is there if you want it.

The nice thing is that though you don’t like the wand mechanics, some of your players might. You can give them the freedom to choose, if you want to let them use the skills command, that’s fine. If they’d rather use the spellbook or a wand, that’s fine too. There’s also a “chest inventory mode” for the wands that you might prefer. They can freely switch between any of these mechanics using the spells they’ve learned.

Hope to talk to you more on Discord :)

**Comment by NathanWolf** [comment]
Oh and I should’ve mentioned that you can right-click on an enchantment table with the wand or spell book to bring up the progress GUI. Or if you want to just try it out, `/cast progressmenu` or to go directly to the spellshop to learn new spells do `/cast spellshop`. The command `/mgive sp 9999` will max out your spell points so you can go nuts buying spells.
