### ISSUE TITLE
wand and crafting_table

### ISSUE THREAD

**Issue by Yukylyu** [elBukkit/MagicPlugin#745]
Hi
My players can put the wand in a craft table :(
spigot 1.16.3
magic 7.10.3

containers:
- crafting_table
- furnace
- furnace_minecart
- brewing_stand
- blast_furnace
- smoker
- dispenser
- hopper
- dropper
- barrel
- chest
- trapped_chest

**Comment by NathanWolf** [comment]
Is that causing issues?

**Comment by Yukyxy** [comment]
I have prevented to put the wand in the crafting table (with the list 'containers'), because if a player puts his wand and breaks the crafting table, the wand falls to the ground and therefore he can lose his wand.

**Comment by NathanWolf** [comment]
Hm, ok i see that's a good point.

Crafting tables are not considered containers (by Minecraft itself) because they don't really hold or store items in the block, it's just a GUI.

I recently allowed crafting with wands so that you could make complex recipes involving wands as ingredients.

I will change that to only allow wand crafting for wands that are "stashable", meaning wands that can be put into containers. I'll let you know here when that's available to test.

**Comment by NathanWolf** [comment]
Ok this change is now live in the latest dev build.

I guess it's also worth noting that recent Minecraft versions seem to have removed the behavior of leftover crafting ingredients dropping on the ground, so I'm not sure this is really a problem anymore anyway.
