### ISSUE TITLE
Bow wands not firing arrows.

### ISSUE THREAD

**Issue by albmagic** [elBukkit/MagicPlugin#750]
Essentially the bug is that when a bow, or crossbow, is turned into a wand it loses its arrow firing capabilities, naturally I assumed that this was just a give and take of the plugin and that one could not coexist with the other, that is until I swapped the items into my off hand and realized they fire perfectly if put into the offhand slot. I'd like to add that while firing in the main hand doesn't shoot any arrows, it does apply the buff Archers Speed which uses the projectile trigger from the RPG spell repository, so this leads me to believe that it is a bug, and not an intentional feature. Thanks for making a great plugin <3

**Comment by NathanWolf** [comment]
I think we addressed this in Discord, the issue was when you added a passive skill to the bow it became the active spell, which does nothing.

This has been fixed in the latest builds by not activating a passive skill on add, but also should have been easily resolved by choosing a different spell to cast.

Please let me know if you have any more issues with these bows.
