### ISSUE TITLE
Shift-clicking a Magic Hat into your inventory causes the hat to be duplicated.

### ISSUE THREAD

**Issue by Prysmane** [elBukkit/MagicPlugin#766]
Minecraft 1.16.3. Shift-clicking a magic hat from a container into your inventory (shift-right clicking or shift-left clicking will work) will leave a magic hat in the chest but also put one on your head, duplicating the item. Buggy behavior can also be seen by shift-clicking a magic hat into a container, which instead puts it on. Having something on your head negates this buggy behavior.

I have also somehow managed to delete an Emerald Sword and Netherite Helmet somehow by doing this, but I cannot replicate it.

**Comment by NathanWolf** [comment]
Thank you for the report!

I forgot about shift+clicking from containers, it's only supposed to be from the player inventory. Should be an easy fix.

I can't account for the vanilla items disappearing though, the plugin should not be doing anything with those. It only reacts to a magic hat click because it has a "wearable" tag.

This will be fixed in 8.0
