### ISSUE TITLE
mwarp and recall spell

### ISSUE THREAD

**Issue by ZadronZSX** [elBukkit/MagicPlugin#783]
I'm not sure if this is a bug or a misunderstanding but setting mwarps does not add them to the recall spell. Am I missing something here or is this a bug? I can do '/mwarp go' but I cannot figure out how to make them available to the recall spell. I'm using the plugin for a 1.13.2 Minecraft Spigot server.

**Comment by NathanWolf** [comment]
Sorry it's not very clear! You need to set an icon for them to show up in Recall. Mainly I didn't want them just showing up automatically, since personally I use a lot of warps for admin things and I don't want players using them.

`/mwarp configure mywarp icon gold_ingot` should make it show up in Recall.

**Comment by NathanWolf** [comment]
You can also use the configure command to set `name` and `description` so it'll look a little nicer in recall.

If you use dynmap, you can set `marker_icon` to make it show up on the map too.

**Comment by ZadronZSX** [comment]
The configure subcommand does not seem to exist for mwarp. 
![Capture](https://user-images.githubusercontent.com/73631009/99296522-86219b00-280c-11eb-8a47-cb7c88f942ed.PNG)

**Comment by NathanWolf** [comment]
You'll need to update to Magic 8.0.1 to be able to add warps to Recall with commands.

If you don't want to update (you should, lots of cool features!) you can add warps manually to Recall by editing the spell configs.

**Comment by ZadronZSX** [comment]
Thank you!
