### ISSUE TITLE
[SUPPORT] Get AP in RPG config

### ISSUE THREAD

**Issue by sakimoe** [elBukkit/MagicPlugin#787]
Hello, I am using the RPG configuration and a question arose, How do I earn the 'AP'? I have been reviewing several .yml files (config, classes, races, etc) and in none of them I manage to capture where they are obtained, so I understood you start with 20 APs by default, up to a maximum of 100, but I do not understand how to get more points or what to do to get them

**Comment by NathanWolf** [comment]
The RPG configs are basically non-existent. It's a very loose example as to how to get started, and something I'd like to expand on over time.

There is currently no progression and no way to earn more AP.

You could get by for now by setting up a shop to trade some large amount of SP for AP, perhaps.

But most of the classes don't really even have any skills or spells or anything.

Basically, until I get a chance to really flesh it out if you want to make something RPG-like with Magic you will be in for a ton of work. If you're really up for this and you have some experience configuration plugins (or ideally configuring Magic) we could perhaps collaborate.

Otherwise if you're looking for a drop-in RPG solution, Magic is not (yet) the right plugin for that. Sorry!

**Comment by sakimoe** [comment]
I see, I tried to do what you said, a store to change sp for ap, but instead of sp you could use xp?
About collaborating, I'm quite a newbie to configuring plugins haha

**Comment by sakimoe** [comment]
Taking advantage, what is the way to earn SP? I understand it was through the wands

**Comment by NathanWolf** [comment]
Ah that should work too- something like this (which I will add as a builtin, but you can add yourself)
```
apshop:
  inherit: buyshop
  parameters:
    cost_type: xp
    items:
    - item: ap:1
      cost: 500
```
You can do `/mconfig editor spells apshop` and drop this in if you want.

**Comment by NathanWolf** [comment]
You earn SP just by casting spells. But again the RPG configs aren't really set up with any spells, so that's the big problem.

https://github.com/elBukkit/MagicPlugin/wiki/Progression

I would *strongly* recommend you spend an hour or so playing with the default survival configs to get a feel for how the basics work before diving in trying to get the RPG configs off the ground.

**Comment by sakimoe** [comment]
ah I see, thank you very much I will use it.
Yes, I will listen to your suggestion, the truth is that I played it for a while but I definitely need to play it longer haha 🤣
