### ISSUE TITLE
Spells have red number? Brooms and Shops.

### ISSUE THREAD

**Issue by meneertimmy** [elBukkit/MagicPlugin#8]
Hello, this plugin is so cool almost everything works fine but brooms are crashing everytime i cant just fly around. How do i fix this? And some spells don't work in survivalmode inventory they have a red 0 on the item. Can i fix this? I want to have shops that sell spells and wand upgrades how do i make that? I hope my issues will be fixed!

**Comment by NathanWolf** [comment]
If there is a red icon on the spell, it can't be cast- either due to permissions, not enough mana, etc. Permissions can be caused by WorldGuard regions, if you are not allowed to break or place blocks.

If you are using WorldGuard, you may also need to allow spawning of entities by other plugins (there is an option in the WG configs for this). Otherwise brooms won't work.
