### ISSUE TITLE
Right-Click Enchanting Table

### ISSUE THREAD

**Issue by TheDarthFather** [elBukkit/MagicPlugin#823]
This does not work as intended (does not open the SpellsMenu).
I noticed this after 8.2, however it may be there from before.
It may be a conflict with the second/third hotbar upgrade ... they both suppose to trigger an action on right-click ...

**Comment by NathanWolf** [comment]
I did try this out after I saw your report (and someone’s confirmation, or maybe vice-versa) on Discord.

But all of the menus seem to be working for me... I thought the other person said that the main menu opened, the spell shop opened but nothing else. 

Trying to think of what could’ve gone wrong there- any chance you could zip up your whole Magic folder so I could try your configs?

**Comment by TheDarthFather** [comment]
Sorry for my late reply. 
Here it is: https://drive.google.com/drive/folders/1uTbi9OhGx5Q7GGrY59Ovmsj66FlhzR4o?usp=sharing

**Comment by NathanWolf** [comment]
No worries at all! It's the holidays- I've been trying to stay away, too.

I think I see the problem, can you please try

`/mconfig example set survival painterly Magic-Bosses`
?

The issue was that "survival" has to be the primary example loaded, otherwise it doesn't modify core settings, it just adds in wands and spells and such.

This is kind of confusing but otherwise things get really messy if mixing together a lot of examples .. I've never come up with a better solution.

**Comment by TheDarthFather** [comment]
I am afraid this did not fix it. Same behaviour.

**Comment by TheDarthFather** [comment]
Worked! Thank you!
