### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException & Failed to read chunk data for task -> server crash

### ISSUE THREAD

**Issue by bobhenl** [elBukkit/MagicPlugin#827]
Hi, my server crashed, these errors happened, don't know exactly why it happened, but it happened probably twice a day, I think it's due to PlayerWorldsPro unload feature in it's plugin https://www.spigotmc.org/resources/%E2%AD%90-playerworldspro-%E2%AD%90-nether-and-the-end-support-async-loading-expiration-1-8-1-16-4.72113/updates

https://pastebin.com/id43GPFv
https://pastebin.com/WDsFVx9w

**Comment by NathanWolf** [comment]
The error from the broom I will look into, but it is probably not related to the crash.

I'm not sure it's a good idea to be reloading worlds on the fly like that, it is definitely the cause of your crash and I doubt the effect errors are related, your server died trying to read chunks for the (presumably unloaded?) world:

> Failed to read chunk data for task: Task for world: 'PW_Notseen' 

What are you doing with this plugin? Seems like a really bad idea to remove worlds unless you *really* need to, maybe just turn off the spawn chunks staying in memory instead?

**Comment by bobhenl** [comment]
https://www.spigotmc.org/resources/%E2%AD%90-playerworldspro-%E2%AD%90-the-nether-and-the-end-support-expiration-1-8-1-16-4.72113/updates

See update page from: Version 5.1.5 - World Unload Update above

**Comment by NathanWolf** [comment]
I am curious what you, specifically, are using this for. It seems to be causing the crash, do you really need it?

**Comment by NathanWolf** [comment]
The error from the broom ended up being if you use the broom from your offhand and then have your wand spell inventory open on landing. Good catch, thank you- this will be fixed in the next stable and dev builds.

I've also changed world comparison in various places to go by reference rather than name, which should prevent the "can't measure distance" errors.

However I don't think I can do anything about the internal spigot region loading error, it does seem like that is caused by reloading worlds so you'll either need to avoid that or narrow it down enough to submit a ticket to Spigot and/or the world management plugin (I think).

**Comment by bobhenl** [comment]
ok, then could be closed here. Thanks for making changes on your side too
