### ISSUE TITLE
Secure spell key loses capability upon rejoin

### ISSUE THREAD

**Issue by Stalros** [elBukkit/MagicPlugin#829]
Secure spell works as described unless a player with a key leaves and rejoins, then a new key is required and the old key goes to waste. This is a bit inconvenient for a group setting as sharing keys with your group becomes much more reliant on you constantly summoning new keys

**Comment by NathanWolf** [comment]
I've been looking at this and it seems to be a Spigot or Minecraft issue- the display name of the item when saved and reloaded changes to a JSON representation that no longer matches the lock type.

Since container locking is a vanilla feature I think this has to be something Spigot is doing.

I'll see if I can find a workaround, else I may need to report it to Spigot and hope for a fix.

**Comment by NathanWolf** [comment]
Did my best to report it, hoping it can be fixed though I don't personally see how yet: https://hub.spigotmc.org/jira/browse/SPIGOT-6307

**Comment by NathanWolf** [comment]
My RP got merged, not sure if it's made its way to Paper or the other forks yet but I've verified Secure works again on latest Spigot.
