### ISSUE TITLE
Wand Duping with Item Swap

### ISSUE THREAD

**Issue by NatsumeLS** [elBukkit/MagicPlugin#845]
### Reproduction steps
1. Hold a Wand
2. Open Spell Menu
3. Open Inventory
4. Click at the Wand and press F at the same time

Result: There will be Two Wands on both hand

### Environment details
`Magic` Version `8.3`
`Yatopia` Build `19`

**Comment by alekso56** [comment]
Related issue; open ocarina, throw ocarina on floor with q.  now there is 2 ocarina.  repeat for infinite profit.

**Comment by NathanWolf** [comment]
Looks like these were a side-effect of a fix for a *different* dupe exploit. Gotta love Minecraft.

I'm pretty sure it's fixed. I was able to do the click+swap dupe one time, but the item I got was a virtual client-side item that disappeared when I swapped the real one back to my hand.

I think I have it fixed in the latest dev/stable builds if you can try it out.

**Comment by alekso56** [comment]
unable to recreate in latest, it's fixed.

**Comment by NathanWolf** [comment]
Great, thank you for letting me know!
