### ISSUE TITLE
Losing Armor With Cloak

### ISSUE THREAD

**Issue by ChrisTVH** [elBukkit/MagicPlugin#870]
![image](https://user-images.githubusercontent.com/58376852/109595015-18af2700-7aea-11eb-838c-109658faa86c.png)

The invisibility spell makes you lose your armor and makes you permanently invisible to mobs until you use the spell again, all armor disappeared from one player except the helmet.

**Comment by NathanWolf** [comment]
Unless I'm misunderstanding you, that is how the spell is intended to work.

- It's a "toggle" spell, meaning you cast it once to turn it on and cast it again to turn it off. It stays on until you run out of mana (which may not happen if you're high level and/or don't cast many other spells)
- It makes you invisible to mobs
- It temporarily removes your armor so you're invisible to players (armor should come back when you turn the spell off)

Please elaborate if I've misunderstood. Does your armor not come back?

**Comment by ChrisTVH** [comment]
His armor did not return only the helmet

**Comment by NathanWolf** [comment]
Aw :( Ok, bummer, sorry. There was an issue that got fixed in 8.4 where you'd lose armor when dying while cloaked.

Can you please try to update?

I'll also look into changing how Cloak works, I store your armor inside of temporary items thinking that'd be safer, but it may be best to just put them in player data.

**Comment by NathanWolf** [comment]
Cloak doesn't replace armor at all any more so I'm *really* hoping this is no longer a problem.
