### ISSUE TITLE
Collapse Spell duplication Bug

### ISSUE THREAD

**Issue by Peda1996** [elBukkit/MagicPlugin#882]
For this to work, one has to use the collapse spell + pistons. With the collapse spell, the diamonds fall on the ground. After that, you have to use the pistons to push these items. The ore on the old place is restored again. And vola, you have duplicated items.

![2021-03-17_12 17 45](https://user-images.githubusercontent.com/1789749/111459592-2cc66b80-871b-11eb-98fd-93d64c5e29c4.png)

Is there any way to fix this bug?

**Comment by NathanWolf** [comment]
Yikes.. probably nothing much you can do on your end, for now you could disable the collapse spell but this will require a fix of the root cause on my side (probably tracking pistons moving blocks)
`/mconfig disable spell collapse`

There are probably other spells, like Blast, that could also make this happen but it might be harder to abuse since the location of the dropped blocks is not as predictable.

**Comment by NathanWolf** [comment]
I've got some improvements to piston handling in the latest dev build: https://jenkins.elmakers.com/job/MagicPlugin/3631/com.elmakers.mine.bukkit.plugins$Magic/artifact/com.elmakers.mine.bukkit.plugins/Magic/8.5-SNAPSHOT/Magic-8.5-SNAPSHOT.jar

I'm not confident that pistons will be handled 100% correctly, but I can no longer dupe blocks at least. There may be some creative way around it, but it should be much harder at least.

Let me know if you are able to try out the dev build, I'm hoping it'll fix the issue for you.

**Comment by Peda1996** [comment]
I tried out the current dev build, and it worked without any issues. --> The duplication contraption is no longer working.

Thanks for your awesome work, and the fast fix 👍
