### ISSUE TITLE
Npc Shops disapear 

### ISSUE THREAD

**Issue by Tekashiteriaki** [elBukkit/MagicPlugin#896]
I keep trying to setup Npc Shops on my server in villages but when i leave a certain radius they go back to the basic villager model and say "There is nothing here for you to buy"
I get no console errors
what can be the problem?

**Comment by NathanWolf** [comment]
I apologize for not getting back to you. This sounds like an issue I have since fixed, especially if you are on 1.17

If you are still having this problem on recent release of Magic, please re-open this ticket and let me know.

The other possibility is if the NPCs are in a WorldGuard region that does not allow plugin spawning.
