### ISSUE TITLE
a simple question - dyed leather armor as wand item

### ISSUE THREAD

**Issue by jshacar** [elBukkit/MagicPlugin#93]
Trying to create a "Goron Tunic" to add to your collection of Zelda themed items.
This item will be a red dyed leather chestplate and it will have max fire resistance potion effect.

I could make a custom item that is dyed red but could not get the potion effect on it.
And I could make a custom wand with the potion effect on it but could not change it to be dyed red.
How can I get the best of both worlds here? Which is the best route - custom item or custom wand? Perhaps you would want to adopt this item idea into future builds of Magic?

**Comment by NathanWolf** [comment]
Yeah this is a good point!

I've been thinking of trying to make wands support magic items, so you could set something like this up.

It's a little tricky because wands historically have had to re-create their items all the time, as Craftbukkit would throw out their custom data and replace it with a new, empty item- but I'm not sure that's needed anymore.

I'll see what I can do about this :)

**Comment by NathanWolf** [comment]
This is supported in the latest Magic release.
