### ISSUE TITLE
Extreme lag on client side with magic installed

### ISSUE THREAD

**Issue by TheHappyHopper** [elBukkit/MagicPlugin#931]
With magic installed, whenever someone gets near a mob, their client will freeze for a solid 10 seconds, causing them to instantly die
This happens no matter how good their computer is
No errors appear in console, this is only a client side issue

**Comment by NathanWolf** [comment]
I don't think that has anything to do with Magic (unless maybe you are talking about magic mobs you have spawned).

Otherwise there is nothing magic does to vanilla mobs, nor anything I can even think of you *could* do to a vanilla mob to make it lag a client, even if you tried.

 Please remove the plugin and see if the problem persists.

**Comment by NathanWolf** [comment]
Please let me know if you still think this is Magic's fault.
