### ISSUE TITLE
Richt-Click Mode Wand Control Doesn't Allow Hotbar Swap

### ISSUE THREAD

**Issue by mercurialmusic** [elBukkit/MagicPlugin#955]
Hello! Having a minor issue with the right-click mode not wanting to allow for hotbar cycling using the drop (or any) key. Also unable to cycle it when the inventory is open, or at all really - just seems to get stuck on whatever you had when you selected that option. Not getting the issue with any of the other modes.

No errors to show, 

Running Magic 9.4.4 on git-Paper-165 (MC: 1.17.1)

Thanks!

**Comment by NathanWolf** [comment]
Whoops! I think I accidentally made "drop" toggle the inventory there instead of the hotbar.

I'll fix it for the next version, but if you want to fix it yourself this should work

`/mconfig configure wand mode_rightclick drop cycle_hotbar`

This will fix the menu item, though- these don't work like slotted upgrades (I have considered changing that..) so any currently broken wands will need to use the controls menu to get fixed.

**Comment by mercurialmusic** [comment]
That did it! Thank you sir!
