### ISSUE TITLE
[Request] Add Filler Option for Magic Shops

### ISSUE THREAD

**Issue by mercurialmusic** [elBukkit/MagicPlugin#967]
Hello! This is kinda late coming, but we've been going through our Magic server after the chaos of updating to Magic 10 and trying to fix some of our ancient configs. We have some custom magic menus that have a glass pane filler that used to work as filler without a price attached, but now players are able to get free glass by clicking the item (we don't really use the magic item values for our economy). Would it be possible to add an option tag for locking items not meant to be sold? Or perhaps is there something in place already that works? I didn't see it in the wiki page at least.

Thanks for the consideration!

**Comment by NathanWolf** [comment]
Sorry about that!
So you just have `icon: glass_pane` with no `item:`?

If so that *does* sound to me like it should be unpurchaseable, and I would call that a bug I want to fix. Certainly not an intention change, though I don't think I ever test using an icon and nothing else on its own.

That said, you can make placeholders using 

`- placeholder: true` 

in place of an item, and then in the main parameters `placeholder_icon: glass_pane`. This should work for now if you're able to update your shops.

**Comment by mercurialmusic** [comment]
Don't apologize! We needed to catch up with the times and 10 kinda forced us to lol. It's been an adventure.

Also I'm sorry for being an idiot because they were under `item:` -- I didn't realize `icon:` was a possibility within the shop's GUI. These are just filler items in the shop kinda like the confirmation filler glass panes. I will try that and the placeholder tag. 

Thanks for the quick response!

**Comment by NathanWolf** [comment]
Oh, thanks for the clarification!

In that case I'm kinda surprised players *weren't* able to take them before, honestly- that sounds like just how you'd make a shop with free items in it!

**Comment by mercurialmusic** [comment]
Yup. That made the difference. Thanks again!
